// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gen/Torrent.proto

package ru.itmo.java.message.tracker;

public interface ClientDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ru.itmo.java.message.tracker.ClientData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 port = 1;</code>
   * @return The port.
   */
  int getPort();

  /**
   * <code>bytes ip = 2;</code>
   * @return The ip.
   */
  com.google.protobuf.ByteString getIp();
}
