// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gen/Torrent.proto

package ru.itmo.java.message.tracker;

/**
 * Protobuf type {@code ru.itmo.java.message.tracker.ClientResponse}
 */
public final class ClientResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ru.itmo.java.message.tracker.ClientResponse)
    ClientResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ClientResponse.newBuilder() to construct.
  private ClientResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ClientResponse() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ClientResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ClientResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            ru.itmo.java.message.tracker.StatResponse.Builder subBuilder = null;
            if (responseCase_ == 1) {
              subBuilder = ((ru.itmo.java.message.tracker.StatResponse) response_).toBuilder();
            }
            response_ =
                input.readMessage(ru.itmo.java.message.tracker.StatResponse.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((ru.itmo.java.message.tracker.StatResponse) response_);
              response_ = subBuilder.buildPartial();
            }
            responseCase_ = 1;
            break;
          }
          case 18: {
            ru.itmo.java.message.tracker.GetResponse.Builder subBuilder = null;
            if (responseCase_ == 2) {
              subBuilder = ((ru.itmo.java.message.tracker.GetResponse) response_).toBuilder();
            }
            response_ =
                input.readMessage(ru.itmo.java.message.tracker.GetResponse.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((ru.itmo.java.message.tracker.GetResponse) response_);
              response_ = subBuilder.buildPartial();
            }
            responseCase_ = 2;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ru.itmo.java.message.tracker.Torrent.internal_static_ru_itmo_java_message_tracker_ClientResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ru.itmo.java.message.tracker.Torrent.internal_static_ru_itmo_java_message_tracker_ClientResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ru.itmo.java.message.tracker.ClientResponse.class, ru.itmo.java.message.tracker.ClientResponse.Builder.class);
  }

  private int responseCase_ = 0;
  private java.lang.Object response_;
  public enum ResponseCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    STATRESPONSE(1),
    GETRESPONSE(2),
    RESPONSE_NOT_SET(0);
    private final int value;
    private ResponseCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ResponseCase valueOf(int value) {
      return forNumber(value);
    }

    public static ResponseCase forNumber(int value) {
      switch (value) {
        case 1: return STATRESPONSE;
        case 2: return GETRESPONSE;
        case 0: return RESPONSE_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public ResponseCase
  getResponseCase() {
    return ResponseCase.forNumber(
        responseCase_);
  }

  public static final int STATRESPONSE_FIELD_NUMBER = 1;
  /**
   * <code>.ru.itmo.java.message.tracker.StatResponse statResponse = 1;</code>
   * @return Whether the statResponse field is set.
   */
  @java.lang.Override
  public boolean hasStatResponse() {
    return responseCase_ == 1;
  }
  /**
   * <code>.ru.itmo.java.message.tracker.StatResponse statResponse = 1;</code>
   * @return The statResponse.
   */
  @java.lang.Override
  public ru.itmo.java.message.tracker.StatResponse getStatResponse() {
    if (responseCase_ == 1) {
       return (ru.itmo.java.message.tracker.StatResponse) response_;
    }
    return ru.itmo.java.message.tracker.StatResponse.getDefaultInstance();
  }
  /**
   * <code>.ru.itmo.java.message.tracker.StatResponse statResponse = 1;</code>
   */
  @java.lang.Override
  public ru.itmo.java.message.tracker.StatResponseOrBuilder getStatResponseOrBuilder() {
    if (responseCase_ == 1) {
       return (ru.itmo.java.message.tracker.StatResponse) response_;
    }
    return ru.itmo.java.message.tracker.StatResponse.getDefaultInstance();
  }

  public static final int GETRESPONSE_FIELD_NUMBER = 2;
  /**
   * <code>.ru.itmo.java.message.tracker.GetResponse getResponse = 2;</code>
   * @return Whether the getResponse field is set.
   */
  @java.lang.Override
  public boolean hasGetResponse() {
    return responseCase_ == 2;
  }
  /**
   * <code>.ru.itmo.java.message.tracker.GetResponse getResponse = 2;</code>
   * @return The getResponse.
   */
  @java.lang.Override
  public ru.itmo.java.message.tracker.GetResponse getGetResponse() {
    if (responseCase_ == 2) {
       return (ru.itmo.java.message.tracker.GetResponse) response_;
    }
    return ru.itmo.java.message.tracker.GetResponse.getDefaultInstance();
  }
  /**
   * <code>.ru.itmo.java.message.tracker.GetResponse getResponse = 2;</code>
   */
  @java.lang.Override
  public ru.itmo.java.message.tracker.GetResponseOrBuilder getGetResponseOrBuilder() {
    if (responseCase_ == 2) {
       return (ru.itmo.java.message.tracker.GetResponse) response_;
    }
    return ru.itmo.java.message.tracker.GetResponse.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (responseCase_ == 1) {
      output.writeMessage(1, (ru.itmo.java.message.tracker.StatResponse) response_);
    }
    if (responseCase_ == 2) {
      output.writeMessage(2, (ru.itmo.java.message.tracker.GetResponse) response_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (responseCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, (ru.itmo.java.message.tracker.StatResponse) response_);
    }
    if (responseCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (ru.itmo.java.message.tracker.GetResponse) response_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ru.itmo.java.message.tracker.ClientResponse)) {
      return super.equals(obj);
    }
    ru.itmo.java.message.tracker.ClientResponse other = (ru.itmo.java.message.tracker.ClientResponse) obj;

    if (!getResponseCase().equals(other.getResponseCase())) return false;
    switch (responseCase_) {
      case 1:
        if (!getStatResponse()
            .equals(other.getStatResponse())) return false;
        break;
      case 2:
        if (!getGetResponse()
            .equals(other.getGetResponse())) return false;
        break;
      case 0:
      default:
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    switch (responseCase_) {
      case 1:
        hash = (37 * hash) + STATRESPONSE_FIELD_NUMBER;
        hash = (53 * hash) + getStatResponse().hashCode();
        break;
      case 2:
        hash = (37 * hash) + GETRESPONSE_FIELD_NUMBER;
        hash = (53 * hash) + getGetResponse().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ru.itmo.java.message.tracker.ClientResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ru.itmo.java.message.tracker.ClientResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ru.itmo.java.message.tracker.ClientResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ru.itmo.java.message.tracker.ClientResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ru.itmo.java.message.tracker.ClientResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ru.itmo.java.message.tracker.ClientResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ru.itmo.java.message.tracker.ClientResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ru.itmo.java.message.tracker.ClientResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ru.itmo.java.message.tracker.ClientResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ru.itmo.java.message.tracker.ClientResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ru.itmo.java.message.tracker.ClientResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ru.itmo.java.message.tracker.ClientResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ru.itmo.java.message.tracker.ClientResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ru.itmo.java.message.tracker.ClientResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ru.itmo.java.message.tracker.ClientResponse)
      ru.itmo.java.message.tracker.ClientResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ru.itmo.java.message.tracker.Torrent.internal_static_ru_itmo_java_message_tracker_ClientResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ru.itmo.java.message.tracker.Torrent.internal_static_ru_itmo_java_message_tracker_ClientResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ru.itmo.java.message.tracker.ClientResponse.class, ru.itmo.java.message.tracker.ClientResponse.Builder.class);
    }

    // Construct using ru.itmo.java.message.tracker.ClientResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      responseCase_ = 0;
      response_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ru.itmo.java.message.tracker.Torrent.internal_static_ru_itmo_java_message_tracker_ClientResponse_descriptor;
    }

    @java.lang.Override
    public ru.itmo.java.message.tracker.ClientResponse getDefaultInstanceForType() {
      return ru.itmo.java.message.tracker.ClientResponse.getDefaultInstance();
    }

    @java.lang.Override
    public ru.itmo.java.message.tracker.ClientResponse build() {
      ru.itmo.java.message.tracker.ClientResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ru.itmo.java.message.tracker.ClientResponse buildPartial() {
      ru.itmo.java.message.tracker.ClientResponse result = new ru.itmo.java.message.tracker.ClientResponse(this);
      if (responseCase_ == 1) {
        if (statResponseBuilder_ == null) {
          result.response_ = response_;
        } else {
          result.response_ = statResponseBuilder_.build();
        }
      }
      if (responseCase_ == 2) {
        if (getResponseBuilder_ == null) {
          result.response_ = response_;
        } else {
          result.response_ = getResponseBuilder_.build();
        }
      }
      result.responseCase_ = responseCase_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ru.itmo.java.message.tracker.ClientResponse) {
        return mergeFrom((ru.itmo.java.message.tracker.ClientResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ru.itmo.java.message.tracker.ClientResponse other) {
      if (other == ru.itmo.java.message.tracker.ClientResponse.getDefaultInstance()) return this;
      switch (other.getResponseCase()) {
        case STATRESPONSE: {
          mergeStatResponse(other.getStatResponse());
          break;
        }
        case GETRESPONSE: {
          mergeGetResponse(other.getGetResponse());
          break;
        }
        case RESPONSE_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ru.itmo.java.message.tracker.ClientResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ru.itmo.java.message.tracker.ClientResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int responseCase_ = 0;
    private java.lang.Object response_;
    public ResponseCase
        getResponseCase() {
      return ResponseCase.forNumber(
          responseCase_);
    }

    public Builder clearResponse() {
      responseCase_ = 0;
      response_ = null;
      onChanged();
      return this;
    }


    private com.google.protobuf.SingleFieldBuilderV3<
        ru.itmo.java.message.tracker.StatResponse, ru.itmo.java.message.tracker.StatResponse.Builder, ru.itmo.java.message.tracker.StatResponseOrBuilder> statResponseBuilder_;
    /**
     * <code>.ru.itmo.java.message.tracker.StatResponse statResponse = 1;</code>
     * @return Whether the statResponse field is set.
     */
    @java.lang.Override
    public boolean hasStatResponse() {
      return responseCase_ == 1;
    }
    /**
     * <code>.ru.itmo.java.message.tracker.StatResponse statResponse = 1;</code>
     * @return The statResponse.
     */
    @java.lang.Override
    public ru.itmo.java.message.tracker.StatResponse getStatResponse() {
      if (statResponseBuilder_ == null) {
        if (responseCase_ == 1) {
          return (ru.itmo.java.message.tracker.StatResponse) response_;
        }
        return ru.itmo.java.message.tracker.StatResponse.getDefaultInstance();
      } else {
        if (responseCase_ == 1) {
          return statResponseBuilder_.getMessage();
        }
        return ru.itmo.java.message.tracker.StatResponse.getDefaultInstance();
      }
    }
    /**
     * <code>.ru.itmo.java.message.tracker.StatResponse statResponse = 1;</code>
     */
    public Builder setStatResponse(ru.itmo.java.message.tracker.StatResponse value) {
      if (statResponseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        response_ = value;
        onChanged();
      } else {
        statResponseBuilder_.setMessage(value);
      }
      responseCase_ = 1;
      return this;
    }
    /**
     * <code>.ru.itmo.java.message.tracker.StatResponse statResponse = 1;</code>
     */
    public Builder setStatResponse(
        ru.itmo.java.message.tracker.StatResponse.Builder builderForValue) {
      if (statResponseBuilder_ == null) {
        response_ = builderForValue.build();
        onChanged();
      } else {
        statResponseBuilder_.setMessage(builderForValue.build());
      }
      responseCase_ = 1;
      return this;
    }
    /**
     * <code>.ru.itmo.java.message.tracker.StatResponse statResponse = 1;</code>
     */
    public Builder mergeStatResponse(ru.itmo.java.message.tracker.StatResponse value) {
      if (statResponseBuilder_ == null) {
        if (responseCase_ == 1 &&
            response_ != ru.itmo.java.message.tracker.StatResponse.getDefaultInstance()) {
          response_ = ru.itmo.java.message.tracker.StatResponse.newBuilder((ru.itmo.java.message.tracker.StatResponse) response_)
              .mergeFrom(value).buildPartial();
        } else {
          response_ = value;
        }
        onChanged();
      } else {
        if (responseCase_ == 1) {
          statResponseBuilder_.mergeFrom(value);
        }
        statResponseBuilder_.setMessage(value);
      }
      responseCase_ = 1;
      return this;
    }
    /**
     * <code>.ru.itmo.java.message.tracker.StatResponse statResponse = 1;</code>
     */
    public Builder clearStatResponse() {
      if (statResponseBuilder_ == null) {
        if (responseCase_ == 1) {
          responseCase_ = 0;
          response_ = null;
          onChanged();
        }
      } else {
        if (responseCase_ == 1) {
          responseCase_ = 0;
          response_ = null;
        }
        statResponseBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.ru.itmo.java.message.tracker.StatResponse statResponse = 1;</code>
     */
    public ru.itmo.java.message.tracker.StatResponse.Builder getStatResponseBuilder() {
      return getStatResponseFieldBuilder().getBuilder();
    }
    /**
     * <code>.ru.itmo.java.message.tracker.StatResponse statResponse = 1;</code>
     */
    @java.lang.Override
    public ru.itmo.java.message.tracker.StatResponseOrBuilder getStatResponseOrBuilder() {
      if ((responseCase_ == 1) && (statResponseBuilder_ != null)) {
        return statResponseBuilder_.getMessageOrBuilder();
      } else {
        if (responseCase_ == 1) {
          return (ru.itmo.java.message.tracker.StatResponse) response_;
        }
        return ru.itmo.java.message.tracker.StatResponse.getDefaultInstance();
      }
    }
    /**
     * <code>.ru.itmo.java.message.tracker.StatResponse statResponse = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ru.itmo.java.message.tracker.StatResponse, ru.itmo.java.message.tracker.StatResponse.Builder, ru.itmo.java.message.tracker.StatResponseOrBuilder> 
        getStatResponseFieldBuilder() {
      if (statResponseBuilder_ == null) {
        if (!(responseCase_ == 1)) {
          response_ = ru.itmo.java.message.tracker.StatResponse.getDefaultInstance();
        }
        statResponseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ru.itmo.java.message.tracker.StatResponse, ru.itmo.java.message.tracker.StatResponse.Builder, ru.itmo.java.message.tracker.StatResponseOrBuilder>(
                (ru.itmo.java.message.tracker.StatResponse) response_,
                getParentForChildren(),
                isClean());
        response_ = null;
      }
      responseCase_ = 1;
      onChanged();;
      return statResponseBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        ru.itmo.java.message.tracker.GetResponse, ru.itmo.java.message.tracker.GetResponse.Builder, ru.itmo.java.message.tracker.GetResponseOrBuilder> getResponseBuilder_;
    /**
     * <code>.ru.itmo.java.message.tracker.GetResponse getResponse = 2;</code>
     * @return Whether the getResponse field is set.
     */
    @java.lang.Override
    public boolean hasGetResponse() {
      return responseCase_ == 2;
    }
    /**
     * <code>.ru.itmo.java.message.tracker.GetResponse getResponse = 2;</code>
     * @return The getResponse.
     */
    @java.lang.Override
    public ru.itmo.java.message.tracker.GetResponse getGetResponse() {
      if (getResponseBuilder_ == null) {
        if (responseCase_ == 2) {
          return (ru.itmo.java.message.tracker.GetResponse) response_;
        }
        return ru.itmo.java.message.tracker.GetResponse.getDefaultInstance();
      } else {
        if (responseCase_ == 2) {
          return getResponseBuilder_.getMessage();
        }
        return ru.itmo.java.message.tracker.GetResponse.getDefaultInstance();
      }
    }
    /**
     * <code>.ru.itmo.java.message.tracker.GetResponse getResponse = 2;</code>
     */
    public Builder setGetResponse(ru.itmo.java.message.tracker.GetResponse value) {
      if (getResponseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        response_ = value;
        onChanged();
      } else {
        getResponseBuilder_.setMessage(value);
      }
      responseCase_ = 2;
      return this;
    }
    /**
     * <code>.ru.itmo.java.message.tracker.GetResponse getResponse = 2;</code>
     */
    public Builder setGetResponse(
        ru.itmo.java.message.tracker.GetResponse.Builder builderForValue) {
      if (getResponseBuilder_ == null) {
        response_ = builderForValue.build();
        onChanged();
      } else {
        getResponseBuilder_.setMessage(builderForValue.build());
      }
      responseCase_ = 2;
      return this;
    }
    /**
     * <code>.ru.itmo.java.message.tracker.GetResponse getResponse = 2;</code>
     */
    public Builder mergeGetResponse(ru.itmo.java.message.tracker.GetResponse value) {
      if (getResponseBuilder_ == null) {
        if (responseCase_ == 2 &&
            response_ != ru.itmo.java.message.tracker.GetResponse.getDefaultInstance()) {
          response_ = ru.itmo.java.message.tracker.GetResponse.newBuilder((ru.itmo.java.message.tracker.GetResponse) response_)
              .mergeFrom(value).buildPartial();
        } else {
          response_ = value;
        }
        onChanged();
      } else {
        if (responseCase_ == 2) {
          getResponseBuilder_.mergeFrom(value);
        }
        getResponseBuilder_.setMessage(value);
      }
      responseCase_ = 2;
      return this;
    }
    /**
     * <code>.ru.itmo.java.message.tracker.GetResponse getResponse = 2;</code>
     */
    public Builder clearGetResponse() {
      if (getResponseBuilder_ == null) {
        if (responseCase_ == 2) {
          responseCase_ = 0;
          response_ = null;
          onChanged();
        }
      } else {
        if (responseCase_ == 2) {
          responseCase_ = 0;
          response_ = null;
        }
        getResponseBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.ru.itmo.java.message.tracker.GetResponse getResponse = 2;</code>
     */
    public ru.itmo.java.message.tracker.GetResponse.Builder getGetResponseBuilder() {
      return getGetResponseFieldBuilder().getBuilder();
    }
    /**
     * <code>.ru.itmo.java.message.tracker.GetResponse getResponse = 2;</code>
     */
    @java.lang.Override
    public ru.itmo.java.message.tracker.GetResponseOrBuilder getGetResponseOrBuilder() {
      if ((responseCase_ == 2) && (getResponseBuilder_ != null)) {
        return getResponseBuilder_.getMessageOrBuilder();
      } else {
        if (responseCase_ == 2) {
          return (ru.itmo.java.message.tracker.GetResponse) response_;
        }
        return ru.itmo.java.message.tracker.GetResponse.getDefaultInstance();
      }
    }
    /**
     * <code>.ru.itmo.java.message.tracker.GetResponse getResponse = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ru.itmo.java.message.tracker.GetResponse, ru.itmo.java.message.tracker.GetResponse.Builder, ru.itmo.java.message.tracker.GetResponseOrBuilder> 
        getGetResponseFieldBuilder() {
      if (getResponseBuilder_ == null) {
        if (!(responseCase_ == 2)) {
          response_ = ru.itmo.java.message.tracker.GetResponse.getDefaultInstance();
        }
        getResponseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ru.itmo.java.message.tracker.GetResponse, ru.itmo.java.message.tracker.GetResponse.Builder, ru.itmo.java.message.tracker.GetResponseOrBuilder>(
                (ru.itmo.java.message.tracker.GetResponse) response_,
                getParentForChildren(),
                isClean());
        response_ = null;
      }
      responseCase_ = 2;
      onChanged();;
      return getResponseBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ru.itmo.java.message.tracker.ClientResponse)
  }

  // @@protoc_insertion_point(class_scope:ru.itmo.java.message.tracker.ClientResponse)
  private static final ru.itmo.java.message.tracker.ClientResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ru.itmo.java.message.tracker.ClientResponse();
  }

  public static ru.itmo.java.message.tracker.ClientResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ClientResponse>
      PARSER = new com.google.protobuf.AbstractParser<ClientResponse>() {
    @java.lang.Override
    public ClientResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ClientResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ClientResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ClientResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ru.itmo.java.message.tracker.ClientResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

