// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gen/Torrent.proto

package ru.itmo.java.message.tracker;

public interface ClientRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ru.itmo.java.message.tracker.ClientRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.ru.itmo.java.message.tracker.StatRequest statRequest = 1;</code>
   * @return Whether the statRequest field is set.
   */
  boolean hasStatRequest();
  /**
   * <code>.ru.itmo.java.message.tracker.StatRequest statRequest = 1;</code>
   * @return The statRequest.
   */
  ru.itmo.java.message.tracker.StatRequest getStatRequest();
  /**
   * <code>.ru.itmo.java.message.tracker.StatRequest statRequest = 1;</code>
   */
  ru.itmo.java.message.tracker.StatRequestOrBuilder getStatRequestOrBuilder();

  /**
   * <code>.ru.itmo.java.message.tracker.GetRequest getRequest = 2;</code>
   * @return Whether the getRequest field is set.
   */
  boolean hasGetRequest();
  /**
   * <code>.ru.itmo.java.message.tracker.GetRequest getRequest = 2;</code>
   * @return The getRequest.
   */
  ru.itmo.java.message.tracker.GetRequest getGetRequest();
  /**
   * <code>.ru.itmo.java.message.tracker.GetRequest getRequest = 2;</code>
   */
  ru.itmo.java.message.tracker.GetRequestOrBuilder getGetRequestOrBuilder();

  public ru.itmo.java.message.tracker.ClientRequest.RequestCase getRequestCase();
}
