// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gen/Torrent.proto

package ru.itmo.java.message.tracker;

public interface GetRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ru.itmo.java.message.tracker.GetRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>int32 part = 2;</code>
   * @return The part.
   */
  int getPart();
}
