// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gen/Torrent.proto

package ru.itmo.java.message.tracker;

public interface ListRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ru.itmo.java.message.tracker.ListRequest)
    com.google.protobuf.MessageOrBuilder {
}
