// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gen/Torrent.proto

package ru.itmo.java.message.tracker;

/**
 * Protobuf type {@code ru.itmo.java.message.tracker.ListResponse}
 */
public final class ListResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ru.itmo.java.message.tracker.ListResponse)
    ListResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ListResponse.newBuilder() to construct.
  private ListResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ListResponse() {
    file_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ListResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ListResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 18: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              file_ = new java.util.ArrayList<ru.itmo.java.message.tracker.FileData>();
              mutable_bitField0_ |= 0x00000001;
            }
            file_.add(
                input.readMessage(ru.itmo.java.message.tracker.FileData.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        file_ = java.util.Collections.unmodifiableList(file_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ru.itmo.java.message.tracker.Torrent.internal_static_ru_itmo_java_message_tracker_ListResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ru.itmo.java.message.tracker.Torrent.internal_static_ru_itmo_java_message_tracker_ListResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ru.itmo.java.message.tracker.ListResponse.class, ru.itmo.java.message.tracker.ListResponse.Builder.class);
  }

  public static final int FILE_FIELD_NUMBER = 2;
  private java.util.List<ru.itmo.java.message.tracker.FileData> file_;
  /**
   * <code>repeated .ru.itmo.java.message.tracker.FileData file = 2;</code>
   */
  @java.lang.Override
  public java.util.List<ru.itmo.java.message.tracker.FileData> getFileList() {
    return file_;
  }
  /**
   * <code>repeated .ru.itmo.java.message.tracker.FileData file = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends ru.itmo.java.message.tracker.FileDataOrBuilder> 
      getFileOrBuilderList() {
    return file_;
  }
  /**
   * <code>repeated .ru.itmo.java.message.tracker.FileData file = 2;</code>
   */
  @java.lang.Override
  public int getFileCount() {
    return file_.size();
  }
  /**
   * <code>repeated .ru.itmo.java.message.tracker.FileData file = 2;</code>
   */
  @java.lang.Override
  public ru.itmo.java.message.tracker.FileData getFile(int index) {
    return file_.get(index);
  }
  /**
   * <code>repeated .ru.itmo.java.message.tracker.FileData file = 2;</code>
   */
  @java.lang.Override
  public ru.itmo.java.message.tracker.FileDataOrBuilder getFileOrBuilder(
      int index) {
    return file_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < file_.size(); i++) {
      output.writeMessage(2, file_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < file_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, file_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ru.itmo.java.message.tracker.ListResponse)) {
      return super.equals(obj);
    }
    ru.itmo.java.message.tracker.ListResponse other = (ru.itmo.java.message.tracker.ListResponse) obj;

    if (!getFileList()
        .equals(other.getFileList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getFileCount() > 0) {
      hash = (37 * hash) + FILE_FIELD_NUMBER;
      hash = (53 * hash) + getFileList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ru.itmo.java.message.tracker.ListResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ru.itmo.java.message.tracker.ListResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ru.itmo.java.message.tracker.ListResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ru.itmo.java.message.tracker.ListResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ru.itmo.java.message.tracker.ListResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ru.itmo.java.message.tracker.ListResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ru.itmo.java.message.tracker.ListResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ru.itmo.java.message.tracker.ListResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ru.itmo.java.message.tracker.ListResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ru.itmo.java.message.tracker.ListResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ru.itmo.java.message.tracker.ListResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ru.itmo.java.message.tracker.ListResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ru.itmo.java.message.tracker.ListResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ru.itmo.java.message.tracker.ListResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ru.itmo.java.message.tracker.ListResponse)
      ru.itmo.java.message.tracker.ListResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ru.itmo.java.message.tracker.Torrent.internal_static_ru_itmo_java_message_tracker_ListResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ru.itmo.java.message.tracker.Torrent.internal_static_ru_itmo_java_message_tracker_ListResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ru.itmo.java.message.tracker.ListResponse.class, ru.itmo.java.message.tracker.ListResponse.Builder.class);
    }

    // Construct using ru.itmo.java.message.tracker.ListResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getFileFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (fileBuilder_ == null) {
        file_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        fileBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ru.itmo.java.message.tracker.Torrent.internal_static_ru_itmo_java_message_tracker_ListResponse_descriptor;
    }

    @java.lang.Override
    public ru.itmo.java.message.tracker.ListResponse getDefaultInstanceForType() {
      return ru.itmo.java.message.tracker.ListResponse.getDefaultInstance();
    }

    @java.lang.Override
    public ru.itmo.java.message.tracker.ListResponse build() {
      ru.itmo.java.message.tracker.ListResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ru.itmo.java.message.tracker.ListResponse buildPartial() {
      ru.itmo.java.message.tracker.ListResponse result = new ru.itmo.java.message.tracker.ListResponse(this);
      int from_bitField0_ = bitField0_;
      if (fileBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          file_ = java.util.Collections.unmodifiableList(file_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.file_ = file_;
      } else {
        result.file_ = fileBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ru.itmo.java.message.tracker.ListResponse) {
        return mergeFrom((ru.itmo.java.message.tracker.ListResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ru.itmo.java.message.tracker.ListResponse other) {
      if (other == ru.itmo.java.message.tracker.ListResponse.getDefaultInstance()) return this;
      if (fileBuilder_ == null) {
        if (!other.file_.isEmpty()) {
          if (file_.isEmpty()) {
            file_ = other.file_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureFileIsMutable();
            file_.addAll(other.file_);
          }
          onChanged();
        }
      } else {
        if (!other.file_.isEmpty()) {
          if (fileBuilder_.isEmpty()) {
            fileBuilder_.dispose();
            fileBuilder_ = null;
            file_ = other.file_;
            bitField0_ = (bitField0_ & ~0x00000001);
            fileBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getFileFieldBuilder() : null;
          } else {
            fileBuilder_.addAllMessages(other.file_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ru.itmo.java.message.tracker.ListResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ru.itmo.java.message.tracker.ListResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<ru.itmo.java.message.tracker.FileData> file_ =
      java.util.Collections.emptyList();
    private void ensureFileIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        file_ = new java.util.ArrayList<ru.itmo.java.message.tracker.FileData>(file_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        ru.itmo.java.message.tracker.FileData, ru.itmo.java.message.tracker.FileData.Builder, ru.itmo.java.message.tracker.FileDataOrBuilder> fileBuilder_;

    /**
     * <code>repeated .ru.itmo.java.message.tracker.FileData file = 2;</code>
     */
    public java.util.List<ru.itmo.java.message.tracker.FileData> getFileList() {
      if (fileBuilder_ == null) {
        return java.util.Collections.unmodifiableList(file_);
      } else {
        return fileBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .ru.itmo.java.message.tracker.FileData file = 2;</code>
     */
    public int getFileCount() {
      if (fileBuilder_ == null) {
        return file_.size();
      } else {
        return fileBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .ru.itmo.java.message.tracker.FileData file = 2;</code>
     */
    public ru.itmo.java.message.tracker.FileData getFile(int index) {
      if (fileBuilder_ == null) {
        return file_.get(index);
      } else {
        return fileBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .ru.itmo.java.message.tracker.FileData file = 2;</code>
     */
    public Builder setFile(
        int index, ru.itmo.java.message.tracker.FileData value) {
      if (fileBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFileIsMutable();
        file_.set(index, value);
        onChanged();
      } else {
        fileBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .ru.itmo.java.message.tracker.FileData file = 2;</code>
     */
    public Builder setFile(
        int index, ru.itmo.java.message.tracker.FileData.Builder builderForValue) {
      if (fileBuilder_ == null) {
        ensureFileIsMutable();
        file_.set(index, builderForValue.build());
        onChanged();
      } else {
        fileBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ru.itmo.java.message.tracker.FileData file = 2;</code>
     */
    public Builder addFile(ru.itmo.java.message.tracker.FileData value) {
      if (fileBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFileIsMutable();
        file_.add(value);
        onChanged();
      } else {
        fileBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .ru.itmo.java.message.tracker.FileData file = 2;</code>
     */
    public Builder addFile(
        int index, ru.itmo.java.message.tracker.FileData value) {
      if (fileBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFileIsMutable();
        file_.add(index, value);
        onChanged();
      } else {
        fileBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .ru.itmo.java.message.tracker.FileData file = 2;</code>
     */
    public Builder addFile(
        ru.itmo.java.message.tracker.FileData.Builder builderForValue) {
      if (fileBuilder_ == null) {
        ensureFileIsMutable();
        file_.add(builderForValue.build());
        onChanged();
      } else {
        fileBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ru.itmo.java.message.tracker.FileData file = 2;</code>
     */
    public Builder addFile(
        int index, ru.itmo.java.message.tracker.FileData.Builder builderForValue) {
      if (fileBuilder_ == null) {
        ensureFileIsMutable();
        file_.add(index, builderForValue.build());
        onChanged();
      } else {
        fileBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ru.itmo.java.message.tracker.FileData file = 2;</code>
     */
    public Builder addAllFile(
        java.lang.Iterable<? extends ru.itmo.java.message.tracker.FileData> values) {
      if (fileBuilder_ == null) {
        ensureFileIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, file_);
        onChanged();
      } else {
        fileBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .ru.itmo.java.message.tracker.FileData file = 2;</code>
     */
    public Builder clearFile() {
      if (fileBuilder_ == null) {
        file_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        fileBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .ru.itmo.java.message.tracker.FileData file = 2;</code>
     */
    public Builder removeFile(int index) {
      if (fileBuilder_ == null) {
        ensureFileIsMutable();
        file_.remove(index);
        onChanged();
      } else {
        fileBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .ru.itmo.java.message.tracker.FileData file = 2;</code>
     */
    public ru.itmo.java.message.tracker.FileData.Builder getFileBuilder(
        int index) {
      return getFileFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .ru.itmo.java.message.tracker.FileData file = 2;</code>
     */
    public ru.itmo.java.message.tracker.FileDataOrBuilder getFileOrBuilder(
        int index) {
      if (fileBuilder_ == null) {
        return file_.get(index);  } else {
        return fileBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .ru.itmo.java.message.tracker.FileData file = 2;</code>
     */
    public java.util.List<? extends ru.itmo.java.message.tracker.FileDataOrBuilder> 
         getFileOrBuilderList() {
      if (fileBuilder_ != null) {
        return fileBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(file_);
      }
    }
    /**
     * <code>repeated .ru.itmo.java.message.tracker.FileData file = 2;</code>
     */
    public ru.itmo.java.message.tracker.FileData.Builder addFileBuilder() {
      return getFileFieldBuilder().addBuilder(
          ru.itmo.java.message.tracker.FileData.getDefaultInstance());
    }
    /**
     * <code>repeated .ru.itmo.java.message.tracker.FileData file = 2;</code>
     */
    public ru.itmo.java.message.tracker.FileData.Builder addFileBuilder(
        int index) {
      return getFileFieldBuilder().addBuilder(
          index, ru.itmo.java.message.tracker.FileData.getDefaultInstance());
    }
    /**
     * <code>repeated .ru.itmo.java.message.tracker.FileData file = 2;</code>
     */
    public java.util.List<ru.itmo.java.message.tracker.FileData.Builder> 
         getFileBuilderList() {
      return getFileFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        ru.itmo.java.message.tracker.FileData, ru.itmo.java.message.tracker.FileData.Builder, ru.itmo.java.message.tracker.FileDataOrBuilder> 
        getFileFieldBuilder() {
      if (fileBuilder_ == null) {
        fileBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            ru.itmo.java.message.tracker.FileData, ru.itmo.java.message.tracker.FileData.Builder, ru.itmo.java.message.tracker.FileDataOrBuilder>(
                file_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        file_ = null;
      }
      return fileBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ru.itmo.java.message.tracker.ListResponse)
  }

  // @@protoc_insertion_point(class_scope:ru.itmo.java.message.tracker.ListResponse)
  private static final ru.itmo.java.message.tracker.ListResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ru.itmo.java.message.tracker.ListResponse();
  }

  public static ru.itmo.java.message.tracker.ListResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ListResponse>
      PARSER = new com.google.protobuf.AbstractParser<ListResponse>() {
    @java.lang.Override
    public ListResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ListResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ListResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ListResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ru.itmo.java.message.tracker.ListResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

