// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gen/Torrent.proto

package ru.itmo.java.message.tracker;

/**
 * Protobuf type {@code ru.itmo.java.message.tracker.SourceResponse}
 */
public final class SourceResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ru.itmo.java.message.tracker.SourceResponse)
    SourceResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SourceResponse.newBuilder() to construct.
  private SourceResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SourceResponse() {
    client_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new SourceResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private SourceResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            count_ = input.readInt32();
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              client_ = new java.util.ArrayList<ru.itmo.java.message.tracker.ClientData>();
              mutable_bitField0_ |= 0x00000001;
            }
            client_.add(
                input.readMessage(ru.itmo.java.message.tracker.ClientData.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        client_ = java.util.Collections.unmodifiableList(client_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ru.itmo.java.message.tracker.Torrent.internal_static_ru_itmo_java_message_tracker_SourceResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ru.itmo.java.message.tracker.Torrent.internal_static_ru_itmo_java_message_tracker_SourceResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ru.itmo.java.message.tracker.SourceResponse.class, ru.itmo.java.message.tracker.SourceResponse.Builder.class);
  }

  public static final int COUNT_FIELD_NUMBER = 1;
  private int count_;
  /**
   * <code>int32 count = 1;</code>
   * @return The count.
   */
  @java.lang.Override
  public int getCount() {
    return count_;
  }

  public static final int CLIENT_FIELD_NUMBER = 2;
  private java.util.List<ru.itmo.java.message.tracker.ClientData> client_;
  /**
   * <code>repeated .ru.itmo.java.message.tracker.ClientData client = 2;</code>
   */
  @java.lang.Override
  public java.util.List<ru.itmo.java.message.tracker.ClientData> getClientList() {
    return client_;
  }
  /**
   * <code>repeated .ru.itmo.java.message.tracker.ClientData client = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends ru.itmo.java.message.tracker.ClientDataOrBuilder> 
      getClientOrBuilderList() {
    return client_;
  }
  /**
   * <code>repeated .ru.itmo.java.message.tracker.ClientData client = 2;</code>
   */
  @java.lang.Override
  public int getClientCount() {
    return client_.size();
  }
  /**
   * <code>repeated .ru.itmo.java.message.tracker.ClientData client = 2;</code>
   */
  @java.lang.Override
  public ru.itmo.java.message.tracker.ClientData getClient(int index) {
    return client_.get(index);
  }
  /**
   * <code>repeated .ru.itmo.java.message.tracker.ClientData client = 2;</code>
   */
  @java.lang.Override
  public ru.itmo.java.message.tracker.ClientDataOrBuilder getClientOrBuilder(
      int index) {
    return client_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (count_ != 0) {
      output.writeInt32(1, count_);
    }
    for (int i = 0; i < client_.size(); i++) {
      output.writeMessage(2, client_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (count_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, count_);
    }
    for (int i = 0; i < client_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, client_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ru.itmo.java.message.tracker.SourceResponse)) {
      return super.equals(obj);
    }
    ru.itmo.java.message.tracker.SourceResponse other = (ru.itmo.java.message.tracker.SourceResponse) obj;

    if (getCount()
        != other.getCount()) return false;
    if (!getClientList()
        .equals(other.getClientList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + COUNT_FIELD_NUMBER;
    hash = (53 * hash) + getCount();
    if (getClientCount() > 0) {
      hash = (37 * hash) + CLIENT_FIELD_NUMBER;
      hash = (53 * hash) + getClientList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ru.itmo.java.message.tracker.SourceResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ru.itmo.java.message.tracker.SourceResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ru.itmo.java.message.tracker.SourceResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ru.itmo.java.message.tracker.SourceResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ru.itmo.java.message.tracker.SourceResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ru.itmo.java.message.tracker.SourceResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ru.itmo.java.message.tracker.SourceResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ru.itmo.java.message.tracker.SourceResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ru.itmo.java.message.tracker.SourceResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ru.itmo.java.message.tracker.SourceResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ru.itmo.java.message.tracker.SourceResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ru.itmo.java.message.tracker.SourceResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ru.itmo.java.message.tracker.SourceResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ru.itmo.java.message.tracker.SourceResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ru.itmo.java.message.tracker.SourceResponse)
      ru.itmo.java.message.tracker.SourceResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ru.itmo.java.message.tracker.Torrent.internal_static_ru_itmo_java_message_tracker_SourceResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ru.itmo.java.message.tracker.Torrent.internal_static_ru_itmo_java_message_tracker_SourceResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ru.itmo.java.message.tracker.SourceResponse.class, ru.itmo.java.message.tracker.SourceResponse.Builder.class);
    }

    // Construct using ru.itmo.java.message.tracker.SourceResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getClientFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      count_ = 0;

      if (clientBuilder_ == null) {
        client_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        clientBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ru.itmo.java.message.tracker.Torrent.internal_static_ru_itmo_java_message_tracker_SourceResponse_descriptor;
    }

    @java.lang.Override
    public ru.itmo.java.message.tracker.SourceResponse getDefaultInstanceForType() {
      return ru.itmo.java.message.tracker.SourceResponse.getDefaultInstance();
    }

    @java.lang.Override
    public ru.itmo.java.message.tracker.SourceResponse build() {
      ru.itmo.java.message.tracker.SourceResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ru.itmo.java.message.tracker.SourceResponse buildPartial() {
      ru.itmo.java.message.tracker.SourceResponse result = new ru.itmo.java.message.tracker.SourceResponse(this);
      int from_bitField0_ = bitField0_;
      result.count_ = count_;
      if (clientBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          client_ = java.util.Collections.unmodifiableList(client_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.client_ = client_;
      } else {
        result.client_ = clientBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ru.itmo.java.message.tracker.SourceResponse) {
        return mergeFrom((ru.itmo.java.message.tracker.SourceResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ru.itmo.java.message.tracker.SourceResponse other) {
      if (other == ru.itmo.java.message.tracker.SourceResponse.getDefaultInstance()) return this;
      if (other.getCount() != 0) {
        setCount(other.getCount());
      }
      if (clientBuilder_ == null) {
        if (!other.client_.isEmpty()) {
          if (client_.isEmpty()) {
            client_ = other.client_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureClientIsMutable();
            client_.addAll(other.client_);
          }
          onChanged();
        }
      } else {
        if (!other.client_.isEmpty()) {
          if (clientBuilder_.isEmpty()) {
            clientBuilder_.dispose();
            clientBuilder_ = null;
            client_ = other.client_;
            bitField0_ = (bitField0_ & ~0x00000001);
            clientBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getClientFieldBuilder() : null;
          } else {
            clientBuilder_.addAllMessages(other.client_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ru.itmo.java.message.tracker.SourceResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ru.itmo.java.message.tracker.SourceResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int count_ ;
    /**
     * <code>int32 count = 1;</code>
     * @return The count.
     */
    @java.lang.Override
    public int getCount() {
      return count_;
    }
    /**
     * <code>int32 count = 1;</code>
     * @param value The count to set.
     * @return This builder for chaining.
     */
    public Builder setCount(int value) {
      
      count_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 count = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearCount() {
      
      count_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<ru.itmo.java.message.tracker.ClientData> client_ =
      java.util.Collections.emptyList();
    private void ensureClientIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        client_ = new java.util.ArrayList<ru.itmo.java.message.tracker.ClientData>(client_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        ru.itmo.java.message.tracker.ClientData, ru.itmo.java.message.tracker.ClientData.Builder, ru.itmo.java.message.tracker.ClientDataOrBuilder> clientBuilder_;

    /**
     * <code>repeated .ru.itmo.java.message.tracker.ClientData client = 2;</code>
     */
    public java.util.List<ru.itmo.java.message.tracker.ClientData> getClientList() {
      if (clientBuilder_ == null) {
        return java.util.Collections.unmodifiableList(client_);
      } else {
        return clientBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .ru.itmo.java.message.tracker.ClientData client = 2;</code>
     */
    public int getClientCount() {
      if (clientBuilder_ == null) {
        return client_.size();
      } else {
        return clientBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .ru.itmo.java.message.tracker.ClientData client = 2;</code>
     */
    public ru.itmo.java.message.tracker.ClientData getClient(int index) {
      if (clientBuilder_ == null) {
        return client_.get(index);
      } else {
        return clientBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .ru.itmo.java.message.tracker.ClientData client = 2;</code>
     */
    public Builder setClient(
        int index, ru.itmo.java.message.tracker.ClientData value) {
      if (clientBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureClientIsMutable();
        client_.set(index, value);
        onChanged();
      } else {
        clientBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .ru.itmo.java.message.tracker.ClientData client = 2;</code>
     */
    public Builder setClient(
        int index, ru.itmo.java.message.tracker.ClientData.Builder builderForValue) {
      if (clientBuilder_ == null) {
        ensureClientIsMutable();
        client_.set(index, builderForValue.build());
        onChanged();
      } else {
        clientBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ru.itmo.java.message.tracker.ClientData client = 2;</code>
     */
    public Builder addClient(ru.itmo.java.message.tracker.ClientData value) {
      if (clientBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureClientIsMutable();
        client_.add(value);
        onChanged();
      } else {
        clientBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .ru.itmo.java.message.tracker.ClientData client = 2;</code>
     */
    public Builder addClient(
        int index, ru.itmo.java.message.tracker.ClientData value) {
      if (clientBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureClientIsMutable();
        client_.add(index, value);
        onChanged();
      } else {
        clientBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .ru.itmo.java.message.tracker.ClientData client = 2;</code>
     */
    public Builder addClient(
        ru.itmo.java.message.tracker.ClientData.Builder builderForValue) {
      if (clientBuilder_ == null) {
        ensureClientIsMutable();
        client_.add(builderForValue.build());
        onChanged();
      } else {
        clientBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ru.itmo.java.message.tracker.ClientData client = 2;</code>
     */
    public Builder addClient(
        int index, ru.itmo.java.message.tracker.ClientData.Builder builderForValue) {
      if (clientBuilder_ == null) {
        ensureClientIsMutable();
        client_.add(index, builderForValue.build());
        onChanged();
      } else {
        clientBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ru.itmo.java.message.tracker.ClientData client = 2;</code>
     */
    public Builder addAllClient(
        java.lang.Iterable<? extends ru.itmo.java.message.tracker.ClientData> values) {
      if (clientBuilder_ == null) {
        ensureClientIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, client_);
        onChanged();
      } else {
        clientBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .ru.itmo.java.message.tracker.ClientData client = 2;</code>
     */
    public Builder clearClient() {
      if (clientBuilder_ == null) {
        client_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        clientBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .ru.itmo.java.message.tracker.ClientData client = 2;</code>
     */
    public Builder removeClient(int index) {
      if (clientBuilder_ == null) {
        ensureClientIsMutable();
        client_.remove(index);
        onChanged();
      } else {
        clientBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .ru.itmo.java.message.tracker.ClientData client = 2;</code>
     */
    public ru.itmo.java.message.tracker.ClientData.Builder getClientBuilder(
        int index) {
      return getClientFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .ru.itmo.java.message.tracker.ClientData client = 2;</code>
     */
    public ru.itmo.java.message.tracker.ClientDataOrBuilder getClientOrBuilder(
        int index) {
      if (clientBuilder_ == null) {
        return client_.get(index);  } else {
        return clientBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .ru.itmo.java.message.tracker.ClientData client = 2;</code>
     */
    public java.util.List<? extends ru.itmo.java.message.tracker.ClientDataOrBuilder> 
         getClientOrBuilderList() {
      if (clientBuilder_ != null) {
        return clientBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(client_);
      }
    }
    /**
     * <code>repeated .ru.itmo.java.message.tracker.ClientData client = 2;</code>
     */
    public ru.itmo.java.message.tracker.ClientData.Builder addClientBuilder() {
      return getClientFieldBuilder().addBuilder(
          ru.itmo.java.message.tracker.ClientData.getDefaultInstance());
    }
    /**
     * <code>repeated .ru.itmo.java.message.tracker.ClientData client = 2;</code>
     */
    public ru.itmo.java.message.tracker.ClientData.Builder addClientBuilder(
        int index) {
      return getClientFieldBuilder().addBuilder(
          index, ru.itmo.java.message.tracker.ClientData.getDefaultInstance());
    }
    /**
     * <code>repeated .ru.itmo.java.message.tracker.ClientData client = 2;</code>
     */
    public java.util.List<ru.itmo.java.message.tracker.ClientData.Builder> 
         getClientBuilderList() {
      return getClientFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        ru.itmo.java.message.tracker.ClientData, ru.itmo.java.message.tracker.ClientData.Builder, ru.itmo.java.message.tracker.ClientDataOrBuilder> 
        getClientFieldBuilder() {
      if (clientBuilder_ == null) {
        clientBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            ru.itmo.java.message.tracker.ClientData, ru.itmo.java.message.tracker.ClientData.Builder, ru.itmo.java.message.tracker.ClientDataOrBuilder>(
                client_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        client_ = null;
      }
      return clientBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ru.itmo.java.message.tracker.SourceResponse)
  }

  // @@protoc_insertion_point(class_scope:ru.itmo.java.message.tracker.SourceResponse)
  private static final ru.itmo.java.message.tracker.SourceResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ru.itmo.java.message.tracker.SourceResponse();
  }

  public static ru.itmo.java.message.tracker.SourceResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SourceResponse>
      PARSER = new com.google.protobuf.AbstractParser<SourceResponse>() {
    @java.lang.Override
    public SourceResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new SourceResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SourceResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SourceResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ru.itmo.java.message.tracker.SourceResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

