// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gen/Torrent.proto

package ru.itmo.java.message.tracker;

public interface StatResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ru.itmo.java.message.tracker.StatResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 count = 1;</code>
   * @return The count.
   */
  int getCount();

  /**
   * <code>repeated int32 part = 2;</code>
   * @return A list containing the part.
   */
  java.util.List<java.lang.Integer> getPartList();
  /**
   * <code>repeated int32 part = 2;</code>
   * @return The count of part.
   */
  int getPartCount();
  /**
   * <code>repeated int32 part = 2;</code>
   * @param index The index of the element to return.
   * @return The part at the given index.
   */
  int getPart(int index);
}
