// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gen/Torrent.proto

package ru.itmo.java.message.tracker;

public final class Torrent {
  private Torrent() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ru_itmo_java_message_tracker_FileData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ru_itmo_java_message_tracker_FileData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ru_itmo_java_message_tracker_ClientData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ru_itmo_java_message_tracker_ClientData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ru_itmo_java_message_tracker_StatRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ru_itmo_java_message_tracker_StatRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ru_itmo_java_message_tracker_StatResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ru_itmo_java_message_tracker_StatResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ru_itmo_java_message_tracker_GetRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ru_itmo_java_message_tracker_GetRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ru_itmo_java_message_tracker_GetResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ru_itmo_java_message_tracker_GetResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ru_itmo_java_message_tracker_ClientRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ru_itmo_java_message_tracker_ClientRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ru_itmo_java_message_tracker_ClientResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ru_itmo_java_message_tracker_ClientResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ru_itmo_java_message_tracker_ListRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ru_itmo_java_message_tracker_ListRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ru_itmo_java_message_tracker_ListResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ru_itmo_java_message_tracker_ListResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ru_itmo_java_message_tracker_UploadRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ru_itmo_java_message_tracker_UploadRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ru_itmo_java_message_tracker_UploadResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ru_itmo_java_message_tracker_UploadResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ru_itmo_java_message_tracker_SourceRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ru_itmo_java_message_tracker_SourceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ru_itmo_java_message_tracker_SourceResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ru_itmo_java_message_tracker_SourceResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ru_itmo_java_message_tracker_UpdateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ru_itmo_java_message_tracker_UpdateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ru_itmo_java_message_tracker_UpdateResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ru_itmo_java_message_tracker_UpdateResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ru_itmo_java_message_tracker_TrackerRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ru_itmo_java_message_tracker_TrackerRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ru_itmo_java_message_tracker_TrackerResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ru_itmo_java_message_tracker_TrackerResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021gen/Torrent.proto\022\034ru.itmo.java.messag" +
      "e.tracker\"2\n\010FileData\022\n\n\002id\030\001 \001(\005\022\014\n\004nam" +
      "e\030\002 \001(\t\022\014\n\004size\030\003 \001(\004\"&\n\nClientData\022\014\n\004p" +
      "ort\030\001 \001(\005\022\n\n\002ip\030\002 \001(\014\"\031\n\013StatRequest\022\n\n\002" +
      "id\030\001 \001(\005\"+\n\014StatResponse\022\r\n\005count\030\001 \001(\005\022" +
      "\014\n\004part\030\002 \003(\005\"&\n\nGetRequest\022\n\n\002id\030\001 \001(\005\022" +
      "\014\n\004part\030\002 \001(\005\"\036\n\013GetResponse\022\017\n\007content\030" +
      "\001 \001(\014\"\234\001\n\rClientRequest\022@\n\013statRequest\030\001" +
      " \001(\0132).ru.itmo.java.message.tracker.Stat" +
      "RequestH\000\022>\n\ngetRequest\030\002 \001(\0132(.ru.itmo." +
      "java.message.tracker.GetRequestH\000B\t\n\007req" +
      "uest\"\242\001\n\016ClientResponse\022B\n\014statResponse\030" +
      "\001 \001(\0132*.ru.itmo.java.message.tracker.Sta" +
      "tResponseH\000\022@\n\013getResponse\030\002 \001(\0132).ru.it" +
      "mo.java.message.tracker.GetResponseH\000B\n\n" +
      "\010response\"\r\n\013ListRequest\"D\n\014ListResponse" +
      "\0224\n\004file\030\002 \003(\0132&.ru.itmo.java.message.tr" +
      "acker.FileData\"E\n\rUploadRequest\0224\n\004file\030" +
      "\001 \001(\0132&.ru.itmo.java.message.tracker.Fil" +
      "eData\"\034\n\016UploadResponse\022\n\n\002id\030\001 \001(\005\"\033\n\rS" +
      "ourceRequest\022\n\n\002id\030\001 \001(\005\"Y\n\016SourceRespon" +
      "se\022\r\n\005count\030\001 \001(\005\0228\n\006client\030\002 \003(\0132(.ru.i" +
      "tmo.java.message.tracker.ClientData\"8\n\rU" +
      "pdateRequest\022\014\n\004port\030\001 \001(\005\022\r\n\005count\030\002 \001(" +
      "\005\022\n\n\002id\030\003 \003(\005\" \n\016UpdateResponse\022\016\n\006statu" +
      "s\030\001 \001(\010\"\257\002\n\016TrackerRequest\022@\n\013listReques" +
      "t\030\001 \001(\0132).ru.itmo.java.message.tracker.L" +
      "istRequestH\000\022D\n\ruploadRequest\030\002 \001(\0132+.ru" +
      ".itmo.java.message.tracker.UploadRequest" +
      "H\000\022D\n\rsourceRequest\030\003 \001(\0132+.ru.itmo.java" +
      ".message.tracker.SourceRequestH\000\022D\n\rupda" +
      "teRequest\030\004 \001(\0132+.ru.itmo.java.message.t" +
      "racker.UpdateRequestH\000B\t\n\007request\"\271\002\n\017Tr" +
      "ackerResponse\022B\n\014listResponse\030\001 \001(\0132*.ru" +
      ".itmo.java.message.tracker.ListResponseH" +
      "\000\022F\n\016uploadResponse\030\002 \001(\0132,.ru.itmo.java" +
      ".message.tracker.UploadResponseH\000\022F\n\016sou" +
      "rceResponse\030\003 \001(\0132,.ru.itmo.java.message" +
      ".tracker.SourceResponseH\000\022F\n\016updateRespo" +
      "nse\030\004 \001(\0132,.ru.itmo.java.message.tracker" +
      ".UpdateResponseH\000B\n\n\010responseB\002P\001b\006proto" +
      "3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ru_itmo_java_message_tracker_FileData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ru_itmo_java_message_tracker_FileData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ru_itmo_java_message_tracker_FileData_descriptor,
        new java.lang.String[] { "Id", "Name", "Size", });
    internal_static_ru_itmo_java_message_tracker_ClientData_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ru_itmo_java_message_tracker_ClientData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ru_itmo_java_message_tracker_ClientData_descriptor,
        new java.lang.String[] { "Port", "Ip", });
    internal_static_ru_itmo_java_message_tracker_StatRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ru_itmo_java_message_tracker_StatRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ru_itmo_java_message_tracker_StatRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_ru_itmo_java_message_tracker_StatResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_ru_itmo_java_message_tracker_StatResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ru_itmo_java_message_tracker_StatResponse_descriptor,
        new java.lang.String[] { "Count", "Part", });
    internal_static_ru_itmo_java_message_tracker_GetRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_ru_itmo_java_message_tracker_GetRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ru_itmo_java_message_tracker_GetRequest_descriptor,
        new java.lang.String[] { "Id", "Part", });
    internal_static_ru_itmo_java_message_tracker_GetResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_ru_itmo_java_message_tracker_GetResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ru_itmo_java_message_tracker_GetResponse_descriptor,
        new java.lang.String[] { "Content", });
    internal_static_ru_itmo_java_message_tracker_ClientRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_ru_itmo_java_message_tracker_ClientRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ru_itmo_java_message_tracker_ClientRequest_descriptor,
        new java.lang.String[] { "StatRequest", "GetRequest", "Request", });
    internal_static_ru_itmo_java_message_tracker_ClientResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_ru_itmo_java_message_tracker_ClientResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ru_itmo_java_message_tracker_ClientResponse_descriptor,
        new java.lang.String[] { "StatResponse", "GetResponse", "Response", });
    internal_static_ru_itmo_java_message_tracker_ListRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_ru_itmo_java_message_tracker_ListRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ru_itmo_java_message_tracker_ListRequest_descriptor,
        new java.lang.String[] { });
    internal_static_ru_itmo_java_message_tracker_ListResponse_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_ru_itmo_java_message_tracker_ListResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ru_itmo_java_message_tracker_ListResponse_descriptor,
        new java.lang.String[] { "File", });
    internal_static_ru_itmo_java_message_tracker_UploadRequest_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_ru_itmo_java_message_tracker_UploadRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ru_itmo_java_message_tracker_UploadRequest_descriptor,
        new java.lang.String[] { "File", });
    internal_static_ru_itmo_java_message_tracker_UploadResponse_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_ru_itmo_java_message_tracker_UploadResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ru_itmo_java_message_tracker_UploadResponse_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_ru_itmo_java_message_tracker_SourceRequest_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_ru_itmo_java_message_tracker_SourceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ru_itmo_java_message_tracker_SourceRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_ru_itmo_java_message_tracker_SourceResponse_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_ru_itmo_java_message_tracker_SourceResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ru_itmo_java_message_tracker_SourceResponse_descriptor,
        new java.lang.String[] { "Count", "Client", });
    internal_static_ru_itmo_java_message_tracker_UpdateRequest_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_ru_itmo_java_message_tracker_UpdateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ru_itmo_java_message_tracker_UpdateRequest_descriptor,
        new java.lang.String[] { "Port", "Count", "Id", });
    internal_static_ru_itmo_java_message_tracker_UpdateResponse_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_ru_itmo_java_message_tracker_UpdateResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ru_itmo_java_message_tracker_UpdateResponse_descriptor,
        new java.lang.String[] { "Status", });
    internal_static_ru_itmo_java_message_tracker_TrackerRequest_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_ru_itmo_java_message_tracker_TrackerRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ru_itmo_java_message_tracker_TrackerRequest_descriptor,
        new java.lang.String[] { "ListRequest", "UploadRequest", "SourceRequest", "UpdateRequest", "Request", });
    internal_static_ru_itmo_java_message_tracker_TrackerResponse_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_ru_itmo_java_message_tracker_TrackerResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ru_itmo_java_message_tracker_TrackerResponse_descriptor,
        new java.lang.String[] { "ListResponse", "UploadResponse", "SourceResponse", "UpdateResponse", "Response", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
