// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gen/Torrent.proto

package ru.itmo.java.message.tracker;

/**
 * Protobuf type {@code ru.itmo.java.message.tracker.TrackerRequest}
 */
public final class TrackerRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ru.itmo.java.message.tracker.TrackerRequest)
    TrackerRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TrackerRequest.newBuilder() to construct.
  private TrackerRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TrackerRequest() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new TrackerRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private TrackerRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            ru.itmo.java.message.tracker.ListRequest.Builder subBuilder = null;
            if (requestCase_ == 1) {
              subBuilder = ((ru.itmo.java.message.tracker.ListRequest) request_).toBuilder();
            }
            request_ =
                input.readMessage(ru.itmo.java.message.tracker.ListRequest.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((ru.itmo.java.message.tracker.ListRequest) request_);
              request_ = subBuilder.buildPartial();
            }
            requestCase_ = 1;
            break;
          }
          case 18: {
            ru.itmo.java.message.tracker.UploadRequest.Builder subBuilder = null;
            if (requestCase_ == 2) {
              subBuilder = ((ru.itmo.java.message.tracker.UploadRequest) request_).toBuilder();
            }
            request_ =
                input.readMessage(ru.itmo.java.message.tracker.UploadRequest.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((ru.itmo.java.message.tracker.UploadRequest) request_);
              request_ = subBuilder.buildPartial();
            }
            requestCase_ = 2;
            break;
          }
          case 26: {
            ru.itmo.java.message.tracker.SourceRequest.Builder subBuilder = null;
            if (requestCase_ == 3) {
              subBuilder = ((ru.itmo.java.message.tracker.SourceRequest) request_).toBuilder();
            }
            request_ =
                input.readMessage(ru.itmo.java.message.tracker.SourceRequest.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((ru.itmo.java.message.tracker.SourceRequest) request_);
              request_ = subBuilder.buildPartial();
            }
            requestCase_ = 3;
            break;
          }
          case 34: {
            ru.itmo.java.message.tracker.UpdateRequest.Builder subBuilder = null;
            if (requestCase_ == 4) {
              subBuilder = ((ru.itmo.java.message.tracker.UpdateRequest) request_).toBuilder();
            }
            request_ =
                input.readMessage(ru.itmo.java.message.tracker.UpdateRequest.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((ru.itmo.java.message.tracker.UpdateRequest) request_);
              request_ = subBuilder.buildPartial();
            }
            requestCase_ = 4;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ru.itmo.java.message.tracker.Torrent.internal_static_ru_itmo_java_message_tracker_TrackerRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ru.itmo.java.message.tracker.Torrent.internal_static_ru_itmo_java_message_tracker_TrackerRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ru.itmo.java.message.tracker.TrackerRequest.class, ru.itmo.java.message.tracker.TrackerRequest.Builder.class);
  }

  private int requestCase_ = 0;
  private java.lang.Object request_;
  public enum RequestCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    LISTREQUEST(1),
    UPLOADREQUEST(2),
    SOURCEREQUEST(3),
    UPDATEREQUEST(4),
    REQUEST_NOT_SET(0);
    private final int value;
    private RequestCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static RequestCase valueOf(int value) {
      return forNumber(value);
    }

    public static RequestCase forNumber(int value) {
      switch (value) {
        case 1: return LISTREQUEST;
        case 2: return UPLOADREQUEST;
        case 3: return SOURCEREQUEST;
        case 4: return UPDATEREQUEST;
        case 0: return REQUEST_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public RequestCase
  getRequestCase() {
    return RequestCase.forNumber(
        requestCase_);
  }

  public static final int LISTREQUEST_FIELD_NUMBER = 1;
  /**
   * <code>.ru.itmo.java.message.tracker.ListRequest listRequest = 1;</code>
   * @return Whether the listRequest field is set.
   */
  @java.lang.Override
  public boolean hasListRequest() {
    return requestCase_ == 1;
  }
  /**
   * <code>.ru.itmo.java.message.tracker.ListRequest listRequest = 1;</code>
   * @return The listRequest.
   */
  @java.lang.Override
  public ru.itmo.java.message.tracker.ListRequest getListRequest() {
    if (requestCase_ == 1) {
       return (ru.itmo.java.message.tracker.ListRequest) request_;
    }
    return ru.itmo.java.message.tracker.ListRequest.getDefaultInstance();
  }
  /**
   * <code>.ru.itmo.java.message.tracker.ListRequest listRequest = 1;</code>
   */
  @java.lang.Override
  public ru.itmo.java.message.tracker.ListRequestOrBuilder getListRequestOrBuilder() {
    if (requestCase_ == 1) {
       return (ru.itmo.java.message.tracker.ListRequest) request_;
    }
    return ru.itmo.java.message.tracker.ListRequest.getDefaultInstance();
  }

  public static final int UPLOADREQUEST_FIELD_NUMBER = 2;
  /**
   * <code>.ru.itmo.java.message.tracker.UploadRequest uploadRequest = 2;</code>
   * @return Whether the uploadRequest field is set.
   */
  @java.lang.Override
  public boolean hasUploadRequest() {
    return requestCase_ == 2;
  }
  /**
   * <code>.ru.itmo.java.message.tracker.UploadRequest uploadRequest = 2;</code>
   * @return The uploadRequest.
   */
  @java.lang.Override
  public ru.itmo.java.message.tracker.UploadRequest getUploadRequest() {
    if (requestCase_ == 2) {
       return (ru.itmo.java.message.tracker.UploadRequest) request_;
    }
    return ru.itmo.java.message.tracker.UploadRequest.getDefaultInstance();
  }
  /**
   * <code>.ru.itmo.java.message.tracker.UploadRequest uploadRequest = 2;</code>
   */
  @java.lang.Override
  public ru.itmo.java.message.tracker.UploadRequestOrBuilder getUploadRequestOrBuilder() {
    if (requestCase_ == 2) {
       return (ru.itmo.java.message.tracker.UploadRequest) request_;
    }
    return ru.itmo.java.message.tracker.UploadRequest.getDefaultInstance();
  }

  public static final int SOURCEREQUEST_FIELD_NUMBER = 3;
  /**
   * <code>.ru.itmo.java.message.tracker.SourceRequest sourceRequest = 3;</code>
   * @return Whether the sourceRequest field is set.
   */
  @java.lang.Override
  public boolean hasSourceRequest() {
    return requestCase_ == 3;
  }
  /**
   * <code>.ru.itmo.java.message.tracker.SourceRequest sourceRequest = 3;</code>
   * @return The sourceRequest.
   */
  @java.lang.Override
  public ru.itmo.java.message.tracker.SourceRequest getSourceRequest() {
    if (requestCase_ == 3) {
       return (ru.itmo.java.message.tracker.SourceRequest) request_;
    }
    return ru.itmo.java.message.tracker.SourceRequest.getDefaultInstance();
  }
  /**
   * <code>.ru.itmo.java.message.tracker.SourceRequest sourceRequest = 3;</code>
   */
  @java.lang.Override
  public ru.itmo.java.message.tracker.SourceRequestOrBuilder getSourceRequestOrBuilder() {
    if (requestCase_ == 3) {
       return (ru.itmo.java.message.tracker.SourceRequest) request_;
    }
    return ru.itmo.java.message.tracker.SourceRequest.getDefaultInstance();
  }

  public static final int UPDATEREQUEST_FIELD_NUMBER = 4;
  /**
   * <code>.ru.itmo.java.message.tracker.UpdateRequest updateRequest = 4;</code>
   * @return Whether the updateRequest field is set.
   */
  @java.lang.Override
  public boolean hasUpdateRequest() {
    return requestCase_ == 4;
  }
  /**
   * <code>.ru.itmo.java.message.tracker.UpdateRequest updateRequest = 4;</code>
   * @return The updateRequest.
   */
  @java.lang.Override
  public ru.itmo.java.message.tracker.UpdateRequest getUpdateRequest() {
    if (requestCase_ == 4) {
       return (ru.itmo.java.message.tracker.UpdateRequest) request_;
    }
    return ru.itmo.java.message.tracker.UpdateRequest.getDefaultInstance();
  }
  /**
   * <code>.ru.itmo.java.message.tracker.UpdateRequest updateRequest = 4;</code>
   */
  @java.lang.Override
  public ru.itmo.java.message.tracker.UpdateRequestOrBuilder getUpdateRequestOrBuilder() {
    if (requestCase_ == 4) {
       return (ru.itmo.java.message.tracker.UpdateRequest) request_;
    }
    return ru.itmo.java.message.tracker.UpdateRequest.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (requestCase_ == 1) {
      output.writeMessage(1, (ru.itmo.java.message.tracker.ListRequest) request_);
    }
    if (requestCase_ == 2) {
      output.writeMessage(2, (ru.itmo.java.message.tracker.UploadRequest) request_);
    }
    if (requestCase_ == 3) {
      output.writeMessage(3, (ru.itmo.java.message.tracker.SourceRequest) request_);
    }
    if (requestCase_ == 4) {
      output.writeMessage(4, (ru.itmo.java.message.tracker.UpdateRequest) request_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (requestCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, (ru.itmo.java.message.tracker.ListRequest) request_);
    }
    if (requestCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (ru.itmo.java.message.tracker.UploadRequest) request_);
    }
    if (requestCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, (ru.itmo.java.message.tracker.SourceRequest) request_);
    }
    if (requestCase_ == 4) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, (ru.itmo.java.message.tracker.UpdateRequest) request_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ru.itmo.java.message.tracker.TrackerRequest)) {
      return super.equals(obj);
    }
    ru.itmo.java.message.tracker.TrackerRequest other = (ru.itmo.java.message.tracker.TrackerRequest) obj;

    if (!getRequestCase().equals(other.getRequestCase())) return false;
    switch (requestCase_) {
      case 1:
        if (!getListRequest()
            .equals(other.getListRequest())) return false;
        break;
      case 2:
        if (!getUploadRequest()
            .equals(other.getUploadRequest())) return false;
        break;
      case 3:
        if (!getSourceRequest()
            .equals(other.getSourceRequest())) return false;
        break;
      case 4:
        if (!getUpdateRequest()
            .equals(other.getUpdateRequest())) return false;
        break;
      case 0:
      default:
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    switch (requestCase_) {
      case 1:
        hash = (37 * hash) + LISTREQUEST_FIELD_NUMBER;
        hash = (53 * hash) + getListRequest().hashCode();
        break;
      case 2:
        hash = (37 * hash) + UPLOADREQUEST_FIELD_NUMBER;
        hash = (53 * hash) + getUploadRequest().hashCode();
        break;
      case 3:
        hash = (37 * hash) + SOURCEREQUEST_FIELD_NUMBER;
        hash = (53 * hash) + getSourceRequest().hashCode();
        break;
      case 4:
        hash = (37 * hash) + UPDATEREQUEST_FIELD_NUMBER;
        hash = (53 * hash) + getUpdateRequest().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ru.itmo.java.message.tracker.TrackerRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ru.itmo.java.message.tracker.TrackerRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ru.itmo.java.message.tracker.TrackerRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ru.itmo.java.message.tracker.TrackerRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ru.itmo.java.message.tracker.TrackerRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ru.itmo.java.message.tracker.TrackerRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ru.itmo.java.message.tracker.TrackerRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ru.itmo.java.message.tracker.TrackerRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ru.itmo.java.message.tracker.TrackerRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ru.itmo.java.message.tracker.TrackerRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ru.itmo.java.message.tracker.TrackerRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ru.itmo.java.message.tracker.TrackerRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ru.itmo.java.message.tracker.TrackerRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ru.itmo.java.message.tracker.TrackerRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ru.itmo.java.message.tracker.TrackerRequest)
      ru.itmo.java.message.tracker.TrackerRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ru.itmo.java.message.tracker.Torrent.internal_static_ru_itmo_java_message_tracker_TrackerRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ru.itmo.java.message.tracker.Torrent.internal_static_ru_itmo_java_message_tracker_TrackerRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ru.itmo.java.message.tracker.TrackerRequest.class, ru.itmo.java.message.tracker.TrackerRequest.Builder.class);
    }

    // Construct using ru.itmo.java.message.tracker.TrackerRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      requestCase_ = 0;
      request_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ru.itmo.java.message.tracker.Torrent.internal_static_ru_itmo_java_message_tracker_TrackerRequest_descriptor;
    }

    @java.lang.Override
    public ru.itmo.java.message.tracker.TrackerRequest getDefaultInstanceForType() {
      return ru.itmo.java.message.tracker.TrackerRequest.getDefaultInstance();
    }

    @java.lang.Override
    public ru.itmo.java.message.tracker.TrackerRequest build() {
      ru.itmo.java.message.tracker.TrackerRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ru.itmo.java.message.tracker.TrackerRequest buildPartial() {
      ru.itmo.java.message.tracker.TrackerRequest result = new ru.itmo.java.message.tracker.TrackerRequest(this);
      if (requestCase_ == 1) {
        if (listRequestBuilder_ == null) {
          result.request_ = request_;
        } else {
          result.request_ = listRequestBuilder_.build();
        }
      }
      if (requestCase_ == 2) {
        if (uploadRequestBuilder_ == null) {
          result.request_ = request_;
        } else {
          result.request_ = uploadRequestBuilder_.build();
        }
      }
      if (requestCase_ == 3) {
        if (sourceRequestBuilder_ == null) {
          result.request_ = request_;
        } else {
          result.request_ = sourceRequestBuilder_.build();
        }
      }
      if (requestCase_ == 4) {
        if (updateRequestBuilder_ == null) {
          result.request_ = request_;
        } else {
          result.request_ = updateRequestBuilder_.build();
        }
      }
      result.requestCase_ = requestCase_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ru.itmo.java.message.tracker.TrackerRequest) {
        return mergeFrom((ru.itmo.java.message.tracker.TrackerRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ru.itmo.java.message.tracker.TrackerRequest other) {
      if (other == ru.itmo.java.message.tracker.TrackerRequest.getDefaultInstance()) return this;
      switch (other.getRequestCase()) {
        case LISTREQUEST: {
          mergeListRequest(other.getListRequest());
          break;
        }
        case UPLOADREQUEST: {
          mergeUploadRequest(other.getUploadRequest());
          break;
        }
        case SOURCEREQUEST: {
          mergeSourceRequest(other.getSourceRequest());
          break;
        }
        case UPDATEREQUEST: {
          mergeUpdateRequest(other.getUpdateRequest());
          break;
        }
        case REQUEST_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ru.itmo.java.message.tracker.TrackerRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ru.itmo.java.message.tracker.TrackerRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int requestCase_ = 0;
    private java.lang.Object request_;
    public RequestCase
        getRequestCase() {
      return RequestCase.forNumber(
          requestCase_);
    }

    public Builder clearRequest() {
      requestCase_ = 0;
      request_ = null;
      onChanged();
      return this;
    }


    private com.google.protobuf.SingleFieldBuilderV3<
        ru.itmo.java.message.tracker.ListRequest, ru.itmo.java.message.tracker.ListRequest.Builder, ru.itmo.java.message.tracker.ListRequestOrBuilder> listRequestBuilder_;
    /**
     * <code>.ru.itmo.java.message.tracker.ListRequest listRequest = 1;</code>
     * @return Whether the listRequest field is set.
     */
    @java.lang.Override
    public boolean hasListRequest() {
      return requestCase_ == 1;
    }
    /**
     * <code>.ru.itmo.java.message.tracker.ListRequest listRequest = 1;</code>
     * @return The listRequest.
     */
    @java.lang.Override
    public ru.itmo.java.message.tracker.ListRequest getListRequest() {
      if (listRequestBuilder_ == null) {
        if (requestCase_ == 1) {
          return (ru.itmo.java.message.tracker.ListRequest) request_;
        }
        return ru.itmo.java.message.tracker.ListRequest.getDefaultInstance();
      } else {
        if (requestCase_ == 1) {
          return listRequestBuilder_.getMessage();
        }
        return ru.itmo.java.message.tracker.ListRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.ru.itmo.java.message.tracker.ListRequest listRequest = 1;</code>
     */
    public Builder setListRequest(ru.itmo.java.message.tracker.ListRequest value) {
      if (listRequestBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        request_ = value;
        onChanged();
      } else {
        listRequestBuilder_.setMessage(value);
      }
      requestCase_ = 1;
      return this;
    }
    /**
     * <code>.ru.itmo.java.message.tracker.ListRequest listRequest = 1;</code>
     */
    public Builder setListRequest(
        ru.itmo.java.message.tracker.ListRequest.Builder builderForValue) {
      if (listRequestBuilder_ == null) {
        request_ = builderForValue.build();
        onChanged();
      } else {
        listRequestBuilder_.setMessage(builderForValue.build());
      }
      requestCase_ = 1;
      return this;
    }
    /**
     * <code>.ru.itmo.java.message.tracker.ListRequest listRequest = 1;</code>
     */
    public Builder mergeListRequest(ru.itmo.java.message.tracker.ListRequest value) {
      if (listRequestBuilder_ == null) {
        if (requestCase_ == 1 &&
            request_ != ru.itmo.java.message.tracker.ListRequest.getDefaultInstance()) {
          request_ = ru.itmo.java.message.tracker.ListRequest.newBuilder((ru.itmo.java.message.tracker.ListRequest) request_)
              .mergeFrom(value).buildPartial();
        } else {
          request_ = value;
        }
        onChanged();
      } else {
        if (requestCase_ == 1) {
          listRequestBuilder_.mergeFrom(value);
        }
        listRequestBuilder_.setMessage(value);
      }
      requestCase_ = 1;
      return this;
    }
    /**
     * <code>.ru.itmo.java.message.tracker.ListRequest listRequest = 1;</code>
     */
    public Builder clearListRequest() {
      if (listRequestBuilder_ == null) {
        if (requestCase_ == 1) {
          requestCase_ = 0;
          request_ = null;
          onChanged();
        }
      } else {
        if (requestCase_ == 1) {
          requestCase_ = 0;
          request_ = null;
        }
        listRequestBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.ru.itmo.java.message.tracker.ListRequest listRequest = 1;</code>
     */
    public ru.itmo.java.message.tracker.ListRequest.Builder getListRequestBuilder() {
      return getListRequestFieldBuilder().getBuilder();
    }
    /**
     * <code>.ru.itmo.java.message.tracker.ListRequest listRequest = 1;</code>
     */
    @java.lang.Override
    public ru.itmo.java.message.tracker.ListRequestOrBuilder getListRequestOrBuilder() {
      if ((requestCase_ == 1) && (listRequestBuilder_ != null)) {
        return listRequestBuilder_.getMessageOrBuilder();
      } else {
        if (requestCase_ == 1) {
          return (ru.itmo.java.message.tracker.ListRequest) request_;
        }
        return ru.itmo.java.message.tracker.ListRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.ru.itmo.java.message.tracker.ListRequest listRequest = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ru.itmo.java.message.tracker.ListRequest, ru.itmo.java.message.tracker.ListRequest.Builder, ru.itmo.java.message.tracker.ListRequestOrBuilder> 
        getListRequestFieldBuilder() {
      if (listRequestBuilder_ == null) {
        if (!(requestCase_ == 1)) {
          request_ = ru.itmo.java.message.tracker.ListRequest.getDefaultInstance();
        }
        listRequestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ru.itmo.java.message.tracker.ListRequest, ru.itmo.java.message.tracker.ListRequest.Builder, ru.itmo.java.message.tracker.ListRequestOrBuilder>(
                (ru.itmo.java.message.tracker.ListRequest) request_,
                getParentForChildren(),
                isClean());
        request_ = null;
      }
      requestCase_ = 1;
      onChanged();;
      return listRequestBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        ru.itmo.java.message.tracker.UploadRequest, ru.itmo.java.message.tracker.UploadRequest.Builder, ru.itmo.java.message.tracker.UploadRequestOrBuilder> uploadRequestBuilder_;
    /**
     * <code>.ru.itmo.java.message.tracker.UploadRequest uploadRequest = 2;</code>
     * @return Whether the uploadRequest field is set.
     */
    @java.lang.Override
    public boolean hasUploadRequest() {
      return requestCase_ == 2;
    }
    /**
     * <code>.ru.itmo.java.message.tracker.UploadRequest uploadRequest = 2;</code>
     * @return The uploadRequest.
     */
    @java.lang.Override
    public ru.itmo.java.message.tracker.UploadRequest getUploadRequest() {
      if (uploadRequestBuilder_ == null) {
        if (requestCase_ == 2) {
          return (ru.itmo.java.message.tracker.UploadRequest) request_;
        }
        return ru.itmo.java.message.tracker.UploadRequest.getDefaultInstance();
      } else {
        if (requestCase_ == 2) {
          return uploadRequestBuilder_.getMessage();
        }
        return ru.itmo.java.message.tracker.UploadRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.ru.itmo.java.message.tracker.UploadRequest uploadRequest = 2;</code>
     */
    public Builder setUploadRequest(ru.itmo.java.message.tracker.UploadRequest value) {
      if (uploadRequestBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        request_ = value;
        onChanged();
      } else {
        uploadRequestBuilder_.setMessage(value);
      }
      requestCase_ = 2;
      return this;
    }
    /**
     * <code>.ru.itmo.java.message.tracker.UploadRequest uploadRequest = 2;</code>
     */
    public Builder setUploadRequest(
        ru.itmo.java.message.tracker.UploadRequest.Builder builderForValue) {
      if (uploadRequestBuilder_ == null) {
        request_ = builderForValue.build();
        onChanged();
      } else {
        uploadRequestBuilder_.setMessage(builderForValue.build());
      }
      requestCase_ = 2;
      return this;
    }
    /**
     * <code>.ru.itmo.java.message.tracker.UploadRequest uploadRequest = 2;</code>
     */
    public Builder mergeUploadRequest(ru.itmo.java.message.tracker.UploadRequest value) {
      if (uploadRequestBuilder_ == null) {
        if (requestCase_ == 2 &&
            request_ != ru.itmo.java.message.tracker.UploadRequest.getDefaultInstance()) {
          request_ = ru.itmo.java.message.tracker.UploadRequest.newBuilder((ru.itmo.java.message.tracker.UploadRequest) request_)
              .mergeFrom(value).buildPartial();
        } else {
          request_ = value;
        }
        onChanged();
      } else {
        if (requestCase_ == 2) {
          uploadRequestBuilder_.mergeFrom(value);
        }
        uploadRequestBuilder_.setMessage(value);
      }
      requestCase_ = 2;
      return this;
    }
    /**
     * <code>.ru.itmo.java.message.tracker.UploadRequest uploadRequest = 2;</code>
     */
    public Builder clearUploadRequest() {
      if (uploadRequestBuilder_ == null) {
        if (requestCase_ == 2) {
          requestCase_ = 0;
          request_ = null;
          onChanged();
        }
      } else {
        if (requestCase_ == 2) {
          requestCase_ = 0;
          request_ = null;
        }
        uploadRequestBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.ru.itmo.java.message.tracker.UploadRequest uploadRequest = 2;</code>
     */
    public ru.itmo.java.message.tracker.UploadRequest.Builder getUploadRequestBuilder() {
      return getUploadRequestFieldBuilder().getBuilder();
    }
    /**
     * <code>.ru.itmo.java.message.tracker.UploadRequest uploadRequest = 2;</code>
     */
    @java.lang.Override
    public ru.itmo.java.message.tracker.UploadRequestOrBuilder getUploadRequestOrBuilder() {
      if ((requestCase_ == 2) && (uploadRequestBuilder_ != null)) {
        return uploadRequestBuilder_.getMessageOrBuilder();
      } else {
        if (requestCase_ == 2) {
          return (ru.itmo.java.message.tracker.UploadRequest) request_;
        }
        return ru.itmo.java.message.tracker.UploadRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.ru.itmo.java.message.tracker.UploadRequest uploadRequest = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ru.itmo.java.message.tracker.UploadRequest, ru.itmo.java.message.tracker.UploadRequest.Builder, ru.itmo.java.message.tracker.UploadRequestOrBuilder> 
        getUploadRequestFieldBuilder() {
      if (uploadRequestBuilder_ == null) {
        if (!(requestCase_ == 2)) {
          request_ = ru.itmo.java.message.tracker.UploadRequest.getDefaultInstance();
        }
        uploadRequestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ru.itmo.java.message.tracker.UploadRequest, ru.itmo.java.message.tracker.UploadRequest.Builder, ru.itmo.java.message.tracker.UploadRequestOrBuilder>(
                (ru.itmo.java.message.tracker.UploadRequest) request_,
                getParentForChildren(),
                isClean());
        request_ = null;
      }
      requestCase_ = 2;
      onChanged();;
      return uploadRequestBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        ru.itmo.java.message.tracker.SourceRequest, ru.itmo.java.message.tracker.SourceRequest.Builder, ru.itmo.java.message.tracker.SourceRequestOrBuilder> sourceRequestBuilder_;
    /**
     * <code>.ru.itmo.java.message.tracker.SourceRequest sourceRequest = 3;</code>
     * @return Whether the sourceRequest field is set.
     */
    @java.lang.Override
    public boolean hasSourceRequest() {
      return requestCase_ == 3;
    }
    /**
     * <code>.ru.itmo.java.message.tracker.SourceRequest sourceRequest = 3;</code>
     * @return The sourceRequest.
     */
    @java.lang.Override
    public ru.itmo.java.message.tracker.SourceRequest getSourceRequest() {
      if (sourceRequestBuilder_ == null) {
        if (requestCase_ == 3) {
          return (ru.itmo.java.message.tracker.SourceRequest) request_;
        }
        return ru.itmo.java.message.tracker.SourceRequest.getDefaultInstance();
      } else {
        if (requestCase_ == 3) {
          return sourceRequestBuilder_.getMessage();
        }
        return ru.itmo.java.message.tracker.SourceRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.ru.itmo.java.message.tracker.SourceRequest sourceRequest = 3;</code>
     */
    public Builder setSourceRequest(ru.itmo.java.message.tracker.SourceRequest value) {
      if (sourceRequestBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        request_ = value;
        onChanged();
      } else {
        sourceRequestBuilder_.setMessage(value);
      }
      requestCase_ = 3;
      return this;
    }
    /**
     * <code>.ru.itmo.java.message.tracker.SourceRequest sourceRequest = 3;</code>
     */
    public Builder setSourceRequest(
        ru.itmo.java.message.tracker.SourceRequest.Builder builderForValue) {
      if (sourceRequestBuilder_ == null) {
        request_ = builderForValue.build();
        onChanged();
      } else {
        sourceRequestBuilder_.setMessage(builderForValue.build());
      }
      requestCase_ = 3;
      return this;
    }
    /**
     * <code>.ru.itmo.java.message.tracker.SourceRequest sourceRequest = 3;</code>
     */
    public Builder mergeSourceRequest(ru.itmo.java.message.tracker.SourceRequest value) {
      if (sourceRequestBuilder_ == null) {
        if (requestCase_ == 3 &&
            request_ != ru.itmo.java.message.tracker.SourceRequest.getDefaultInstance()) {
          request_ = ru.itmo.java.message.tracker.SourceRequest.newBuilder((ru.itmo.java.message.tracker.SourceRequest) request_)
              .mergeFrom(value).buildPartial();
        } else {
          request_ = value;
        }
        onChanged();
      } else {
        if (requestCase_ == 3) {
          sourceRequestBuilder_.mergeFrom(value);
        }
        sourceRequestBuilder_.setMessage(value);
      }
      requestCase_ = 3;
      return this;
    }
    /**
     * <code>.ru.itmo.java.message.tracker.SourceRequest sourceRequest = 3;</code>
     */
    public Builder clearSourceRequest() {
      if (sourceRequestBuilder_ == null) {
        if (requestCase_ == 3) {
          requestCase_ = 0;
          request_ = null;
          onChanged();
        }
      } else {
        if (requestCase_ == 3) {
          requestCase_ = 0;
          request_ = null;
        }
        sourceRequestBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.ru.itmo.java.message.tracker.SourceRequest sourceRequest = 3;</code>
     */
    public ru.itmo.java.message.tracker.SourceRequest.Builder getSourceRequestBuilder() {
      return getSourceRequestFieldBuilder().getBuilder();
    }
    /**
     * <code>.ru.itmo.java.message.tracker.SourceRequest sourceRequest = 3;</code>
     */
    @java.lang.Override
    public ru.itmo.java.message.tracker.SourceRequestOrBuilder getSourceRequestOrBuilder() {
      if ((requestCase_ == 3) && (sourceRequestBuilder_ != null)) {
        return sourceRequestBuilder_.getMessageOrBuilder();
      } else {
        if (requestCase_ == 3) {
          return (ru.itmo.java.message.tracker.SourceRequest) request_;
        }
        return ru.itmo.java.message.tracker.SourceRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.ru.itmo.java.message.tracker.SourceRequest sourceRequest = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ru.itmo.java.message.tracker.SourceRequest, ru.itmo.java.message.tracker.SourceRequest.Builder, ru.itmo.java.message.tracker.SourceRequestOrBuilder> 
        getSourceRequestFieldBuilder() {
      if (sourceRequestBuilder_ == null) {
        if (!(requestCase_ == 3)) {
          request_ = ru.itmo.java.message.tracker.SourceRequest.getDefaultInstance();
        }
        sourceRequestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ru.itmo.java.message.tracker.SourceRequest, ru.itmo.java.message.tracker.SourceRequest.Builder, ru.itmo.java.message.tracker.SourceRequestOrBuilder>(
                (ru.itmo.java.message.tracker.SourceRequest) request_,
                getParentForChildren(),
                isClean());
        request_ = null;
      }
      requestCase_ = 3;
      onChanged();;
      return sourceRequestBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        ru.itmo.java.message.tracker.UpdateRequest, ru.itmo.java.message.tracker.UpdateRequest.Builder, ru.itmo.java.message.tracker.UpdateRequestOrBuilder> updateRequestBuilder_;
    /**
     * <code>.ru.itmo.java.message.tracker.UpdateRequest updateRequest = 4;</code>
     * @return Whether the updateRequest field is set.
     */
    @java.lang.Override
    public boolean hasUpdateRequest() {
      return requestCase_ == 4;
    }
    /**
     * <code>.ru.itmo.java.message.tracker.UpdateRequest updateRequest = 4;</code>
     * @return The updateRequest.
     */
    @java.lang.Override
    public ru.itmo.java.message.tracker.UpdateRequest getUpdateRequest() {
      if (updateRequestBuilder_ == null) {
        if (requestCase_ == 4) {
          return (ru.itmo.java.message.tracker.UpdateRequest) request_;
        }
        return ru.itmo.java.message.tracker.UpdateRequest.getDefaultInstance();
      } else {
        if (requestCase_ == 4) {
          return updateRequestBuilder_.getMessage();
        }
        return ru.itmo.java.message.tracker.UpdateRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.ru.itmo.java.message.tracker.UpdateRequest updateRequest = 4;</code>
     */
    public Builder setUpdateRequest(ru.itmo.java.message.tracker.UpdateRequest value) {
      if (updateRequestBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        request_ = value;
        onChanged();
      } else {
        updateRequestBuilder_.setMessage(value);
      }
      requestCase_ = 4;
      return this;
    }
    /**
     * <code>.ru.itmo.java.message.tracker.UpdateRequest updateRequest = 4;</code>
     */
    public Builder setUpdateRequest(
        ru.itmo.java.message.tracker.UpdateRequest.Builder builderForValue) {
      if (updateRequestBuilder_ == null) {
        request_ = builderForValue.build();
        onChanged();
      } else {
        updateRequestBuilder_.setMessage(builderForValue.build());
      }
      requestCase_ = 4;
      return this;
    }
    /**
     * <code>.ru.itmo.java.message.tracker.UpdateRequest updateRequest = 4;</code>
     */
    public Builder mergeUpdateRequest(ru.itmo.java.message.tracker.UpdateRequest value) {
      if (updateRequestBuilder_ == null) {
        if (requestCase_ == 4 &&
            request_ != ru.itmo.java.message.tracker.UpdateRequest.getDefaultInstance()) {
          request_ = ru.itmo.java.message.tracker.UpdateRequest.newBuilder((ru.itmo.java.message.tracker.UpdateRequest) request_)
              .mergeFrom(value).buildPartial();
        } else {
          request_ = value;
        }
        onChanged();
      } else {
        if (requestCase_ == 4) {
          updateRequestBuilder_.mergeFrom(value);
        }
        updateRequestBuilder_.setMessage(value);
      }
      requestCase_ = 4;
      return this;
    }
    /**
     * <code>.ru.itmo.java.message.tracker.UpdateRequest updateRequest = 4;</code>
     */
    public Builder clearUpdateRequest() {
      if (updateRequestBuilder_ == null) {
        if (requestCase_ == 4) {
          requestCase_ = 0;
          request_ = null;
          onChanged();
        }
      } else {
        if (requestCase_ == 4) {
          requestCase_ = 0;
          request_ = null;
        }
        updateRequestBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.ru.itmo.java.message.tracker.UpdateRequest updateRequest = 4;</code>
     */
    public ru.itmo.java.message.tracker.UpdateRequest.Builder getUpdateRequestBuilder() {
      return getUpdateRequestFieldBuilder().getBuilder();
    }
    /**
     * <code>.ru.itmo.java.message.tracker.UpdateRequest updateRequest = 4;</code>
     */
    @java.lang.Override
    public ru.itmo.java.message.tracker.UpdateRequestOrBuilder getUpdateRequestOrBuilder() {
      if ((requestCase_ == 4) && (updateRequestBuilder_ != null)) {
        return updateRequestBuilder_.getMessageOrBuilder();
      } else {
        if (requestCase_ == 4) {
          return (ru.itmo.java.message.tracker.UpdateRequest) request_;
        }
        return ru.itmo.java.message.tracker.UpdateRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.ru.itmo.java.message.tracker.UpdateRequest updateRequest = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ru.itmo.java.message.tracker.UpdateRequest, ru.itmo.java.message.tracker.UpdateRequest.Builder, ru.itmo.java.message.tracker.UpdateRequestOrBuilder> 
        getUpdateRequestFieldBuilder() {
      if (updateRequestBuilder_ == null) {
        if (!(requestCase_ == 4)) {
          request_ = ru.itmo.java.message.tracker.UpdateRequest.getDefaultInstance();
        }
        updateRequestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ru.itmo.java.message.tracker.UpdateRequest, ru.itmo.java.message.tracker.UpdateRequest.Builder, ru.itmo.java.message.tracker.UpdateRequestOrBuilder>(
                (ru.itmo.java.message.tracker.UpdateRequest) request_,
                getParentForChildren(),
                isClean());
        request_ = null;
      }
      requestCase_ = 4;
      onChanged();;
      return updateRequestBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ru.itmo.java.message.tracker.TrackerRequest)
  }

  // @@protoc_insertion_point(class_scope:ru.itmo.java.message.tracker.TrackerRequest)
  private static final ru.itmo.java.message.tracker.TrackerRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ru.itmo.java.message.tracker.TrackerRequest();
  }

  public static ru.itmo.java.message.tracker.TrackerRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TrackerRequest>
      PARSER = new com.google.protobuf.AbstractParser<TrackerRequest>() {
    @java.lang.Override
    public TrackerRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TrackerRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TrackerRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TrackerRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ru.itmo.java.message.tracker.TrackerRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

