// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gen/Torrent.proto

package ru.itmo.java.message.tracker;

public interface TrackerRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ru.itmo.java.message.tracker.TrackerRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.ru.itmo.java.message.tracker.ListRequest listRequest = 1;</code>
   * @return Whether the listRequest field is set.
   */
  boolean hasListRequest();
  /**
   * <code>.ru.itmo.java.message.tracker.ListRequest listRequest = 1;</code>
   * @return The listRequest.
   */
  ru.itmo.java.message.tracker.ListRequest getListRequest();
  /**
   * <code>.ru.itmo.java.message.tracker.ListRequest listRequest = 1;</code>
   */
  ru.itmo.java.message.tracker.ListRequestOrBuilder getListRequestOrBuilder();

  /**
   * <code>.ru.itmo.java.message.tracker.UploadRequest uploadRequest = 2;</code>
   * @return Whether the uploadRequest field is set.
   */
  boolean hasUploadRequest();
  /**
   * <code>.ru.itmo.java.message.tracker.UploadRequest uploadRequest = 2;</code>
   * @return The uploadRequest.
   */
  ru.itmo.java.message.tracker.UploadRequest getUploadRequest();
  /**
   * <code>.ru.itmo.java.message.tracker.UploadRequest uploadRequest = 2;</code>
   */
  ru.itmo.java.message.tracker.UploadRequestOrBuilder getUploadRequestOrBuilder();

  /**
   * <code>.ru.itmo.java.message.tracker.SourceRequest sourceRequest = 3;</code>
   * @return Whether the sourceRequest field is set.
   */
  boolean hasSourceRequest();
  /**
   * <code>.ru.itmo.java.message.tracker.SourceRequest sourceRequest = 3;</code>
   * @return The sourceRequest.
   */
  ru.itmo.java.message.tracker.SourceRequest getSourceRequest();
  /**
   * <code>.ru.itmo.java.message.tracker.SourceRequest sourceRequest = 3;</code>
   */
  ru.itmo.java.message.tracker.SourceRequestOrBuilder getSourceRequestOrBuilder();

  /**
   * <code>.ru.itmo.java.message.tracker.UpdateRequest updateRequest = 4;</code>
   * @return Whether the updateRequest field is set.
   */
  boolean hasUpdateRequest();
  /**
   * <code>.ru.itmo.java.message.tracker.UpdateRequest updateRequest = 4;</code>
   * @return The updateRequest.
   */
  ru.itmo.java.message.tracker.UpdateRequest getUpdateRequest();
  /**
   * <code>.ru.itmo.java.message.tracker.UpdateRequest updateRequest = 4;</code>
   */
  ru.itmo.java.message.tracker.UpdateRequestOrBuilder getUpdateRequestOrBuilder();

  public ru.itmo.java.message.tracker.TrackerRequest.RequestCase getRequestCase();
}
