// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gen/Torrent.proto

package ru.itmo.java.message.tracker;

/**
 * Protobuf type {@code ru.itmo.java.message.tracker.TrackerResponse}
 */
public final class TrackerResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ru.itmo.java.message.tracker.TrackerResponse)
    TrackerResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TrackerResponse.newBuilder() to construct.
  private TrackerResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TrackerResponse() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new TrackerResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private TrackerResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            ru.itmo.java.message.tracker.ListResponse.Builder subBuilder = null;
            if (responseCase_ == 1) {
              subBuilder = ((ru.itmo.java.message.tracker.ListResponse) response_).toBuilder();
            }
            response_ =
                input.readMessage(ru.itmo.java.message.tracker.ListResponse.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((ru.itmo.java.message.tracker.ListResponse) response_);
              response_ = subBuilder.buildPartial();
            }
            responseCase_ = 1;
            break;
          }
          case 18: {
            ru.itmo.java.message.tracker.UploadResponse.Builder subBuilder = null;
            if (responseCase_ == 2) {
              subBuilder = ((ru.itmo.java.message.tracker.UploadResponse) response_).toBuilder();
            }
            response_ =
                input.readMessage(ru.itmo.java.message.tracker.UploadResponse.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((ru.itmo.java.message.tracker.UploadResponse) response_);
              response_ = subBuilder.buildPartial();
            }
            responseCase_ = 2;
            break;
          }
          case 26: {
            ru.itmo.java.message.tracker.SourceResponse.Builder subBuilder = null;
            if (responseCase_ == 3) {
              subBuilder = ((ru.itmo.java.message.tracker.SourceResponse) response_).toBuilder();
            }
            response_ =
                input.readMessage(ru.itmo.java.message.tracker.SourceResponse.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((ru.itmo.java.message.tracker.SourceResponse) response_);
              response_ = subBuilder.buildPartial();
            }
            responseCase_ = 3;
            break;
          }
          case 34: {
            ru.itmo.java.message.tracker.UpdateResponse.Builder subBuilder = null;
            if (responseCase_ == 4) {
              subBuilder = ((ru.itmo.java.message.tracker.UpdateResponse) response_).toBuilder();
            }
            response_ =
                input.readMessage(ru.itmo.java.message.tracker.UpdateResponse.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((ru.itmo.java.message.tracker.UpdateResponse) response_);
              response_ = subBuilder.buildPartial();
            }
            responseCase_ = 4;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ru.itmo.java.message.tracker.Torrent.internal_static_ru_itmo_java_message_tracker_TrackerResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ru.itmo.java.message.tracker.Torrent.internal_static_ru_itmo_java_message_tracker_TrackerResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ru.itmo.java.message.tracker.TrackerResponse.class, ru.itmo.java.message.tracker.TrackerResponse.Builder.class);
  }

  private int responseCase_ = 0;
  private java.lang.Object response_;
  public enum ResponseCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    LISTRESPONSE(1),
    UPLOADRESPONSE(2),
    SOURCERESPONSE(3),
    UPDATERESPONSE(4),
    RESPONSE_NOT_SET(0);
    private final int value;
    private ResponseCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ResponseCase valueOf(int value) {
      return forNumber(value);
    }

    public static ResponseCase forNumber(int value) {
      switch (value) {
        case 1: return LISTRESPONSE;
        case 2: return UPLOADRESPONSE;
        case 3: return SOURCERESPONSE;
        case 4: return UPDATERESPONSE;
        case 0: return RESPONSE_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public ResponseCase
  getResponseCase() {
    return ResponseCase.forNumber(
        responseCase_);
  }

  public static final int LISTRESPONSE_FIELD_NUMBER = 1;
  /**
   * <code>.ru.itmo.java.message.tracker.ListResponse listResponse = 1;</code>
   * @return Whether the listResponse field is set.
   */
  @java.lang.Override
  public boolean hasListResponse() {
    return responseCase_ == 1;
  }
  /**
   * <code>.ru.itmo.java.message.tracker.ListResponse listResponse = 1;</code>
   * @return The listResponse.
   */
  @java.lang.Override
  public ru.itmo.java.message.tracker.ListResponse getListResponse() {
    if (responseCase_ == 1) {
       return (ru.itmo.java.message.tracker.ListResponse) response_;
    }
    return ru.itmo.java.message.tracker.ListResponse.getDefaultInstance();
  }
  /**
   * <code>.ru.itmo.java.message.tracker.ListResponse listResponse = 1;</code>
   */
  @java.lang.Override
  public ru.itmo.java.message.tracker.ListResponseOrBuilder getListResponseOrBuilder() {
    if (responseCase_ == 1) {
       return (ru.itmo.java.message.tracker.ListResponse) response_;
    }
    return ru.itmo.java.message.tracker.ListResponse.getDefaultInstance();
  }

  public static final int UPLOADRESPONSE_FIELD_NUMBER = 2;
  /**
   * <code>.ru.itmo.java.message.tracker.UploadResponse uploadResponse = 2;</code>
   * @return Whether the uploadResponse field is set.
   */
  @java.lang.Override
  public boolean hasUploadResponse() {
    return responseCase_ == 2;
  }
  /**
   * <code>.ru.itmo.java.message.tracker.UploadResponse uploadResponse = 2;</code>
   * @return The uploadResponse.
   */
  @java.lang.Override
  public ru.itmo.java.message.tracker.UploadResponse getUploadResponse() {
    if (responseCase_ == 2) {
       return (ru.itmo.java.message.tracker.UploadResponse) response_;
    }
    return ru.itmo.java.message.tracker.UploadResponse.getDefaultInstance();
  }
  /**
   * <code>.ru.itmo.java.message.tracker.UploadResponse uploadResponse = 2;</code>
   */
  @java.lang.Override
  public ru.itmo.java.message.tracker.UploadResponseOrBuilder getUploadResponseOrBuilder() {
    if (responseCase_ == 2) {
       return (ru.itmo.java.message.tracker.UploadResponse) response_;
    }
    return ru.itmo.java.message.tracker.UploadResponse.getDefaultInstance();
  }

  public static final int SOURCERESPONSE_FIELD_NUMBER = 3;
  /**
   * <code>.ru.itmo.java.message.tracker.SourceResponse sourceResponse = 3;</code>
   * @return Whether the sourceResponse field is set.
   */
  @java.lang.Override
  public boolean hasSourceResponse() {
    return responseCase_ == 3;
  }
  /**
   * <code>.ru.itmo.java.message.tracker.SourceResponse sourceResponse = 3;</code>
   * @return The sourceResponse.
   */
  @java.lang.Override
  public ru.itmo.java.message.tracker.SourceResponse getSourceResponse() {
    if (responseCase_ == 3) {
       return (ru.itmo.java.message.tracker.SourceResponse) response_;
    }
    return ru.itmo.java.message.tracker.SourceResponse.getDefaultInstance();
  }
  /**
   * <code>.ru.itmo.java.message.tracker.SourceResponse sourceResponse = 3;</code>
   */
  @java.lang.Override
  public ru.itmo.java.message.tracker.SourceResponseOrBuilder getSourceResponseOrBuilder() {
    if (responseCase_ == 3) {
       return (ru.itmo.java.message.tracker.SourceResponse) response_;
    }
    return ru.itmo.java.message.tracker.SourceResponse.getDefaultInstance();
  }

  public static final int UPDATERESPONSE_FIELD_NUMBER = 4;
  /**
   * <code>.ru.itmo.java.message.tracker.UpdateResponse updateResponse = 4;</code>
   * @return Whether the updateResponse field is set.
   */
  @java.lang.Override
  public boolean hasUpdateResponse() {
    return responseCase_ == 4;
  }
  /**
   * <code>.ru.itmo.java.message.tracker.UpdateResponse updateResponse = 4;</code>
   * @return The updateResponse.
   */
  @java.lang.Override
  public ru.itmo.java.message.tracker.UpdateResponse getUpdateResponse() {
    if (responseCase_ == 4) {
       return (ru.itmo.java.message.tracker.UpdateResponse) response_;
    }
    return ru.itmo.java.message.tracker.UpdateResponse.getDefaultInstance();
  }
  /**
   * <code>.ru.itmo.java.message.tracker.UpdateResponse updateResponse = 4;</code>
   */
  @java.lang.Override
  public ru.itmo.java.message.tracker.UpdateResponseOrBuilder getUpdateResponseOrBuilder() {
    if (responseCase_ == 4) {
       return (ru.itmo.java.message.tracker.UpdateResponse) response_;
    }
    return ru.itmo.java.message.tracker.UpdateResponse.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (responseCase_ == 1) {
      output.writeMessage(1, (ru.itmo.java.message.tracker.ListResponse) response_);
    }
    if (responseCase_ == 2) {
      output.writeMessage(2, (ru.itmo.java.message.tracker.UploadResponse) response_);
    }
    if (responseCase_ == 3) {
      output.writeMessage(3, (ru.itmo.java.message.tracker.SourceResponse) response_);
    }
    if (responseCase_ == 4) {
      output.writeMessage(4, (ru.itmo.java.message.tracker.UpdateResponse) response_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (responseCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, (ru.itmo.java.message.tracker.ListResponse) response_);
    }
    if (responseCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (ru.itmo.java.message.tracker.UploadResponse) response_);
    }
    if (responseCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, (ru.itmo.java.message.tracker.SourceResponse) response_);
    }
    if (responseCase_ == 4) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, (ru.itmo.java.message.tracker.UpdateResponse) response_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ru.itmo.java.message.tracker.TrackerResponse)) {
      return super.equals(obj);
    }
    ru.itmo.java.message.tracker.TrackerResponse other = (ru.itmo.java.message.tracker.TrackerResponse) obj;

    if (!getResponseCase().equals(other.getResponseCase())) return false;
    switch (responseCase_) {
      case 1:
        if (!getListResponse()
            .equals(other.getListResponse())) return false;
        break;
      case 2:
        if (!getUploadResponse()
            .equals(other.getUploadResponse())) return false;
        break;
      case 3:
        if (!getSourceResponse()
            .equals(other.getSourceResponse())) return false;
        break;
      case 4:
        if (!getUpdateResponse()
            .equals(other.getUpdateResponse())) return false;
        break;
      case 0:
      default:
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    switch (responseCase_) {
      case 1:
        hash = (37 * hash) + LISTRESPONSE_FIELD_NUMBER;
        hash = (53 * hash) + getListResponse().hashCode();
        break;
      case 2:
        hash = (37 * hash) + UPLOADRESPONSE_FIELD_NUMBER;
        hash = (53 * hash) + getUploadResponse().hashCode();
        break;
      case 3:
        hash = (37 * hash) + SOURCERESPONSE_FIELD_NUMBER;
        hash = (53 * hash) + getSourceResponse().hashCode();
        break;
      case 4:
        hash = (37 * hash) + UPDATERESPONSE_FIELD_NUMBER;
        hash = (53 * hash) + getUpdateResponse().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ru.itmo.java.message.tracker.TrackerResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ru.itmo.java.message.tracker.TrackerResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ru.itmo.java.message.tracker.TrackerResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ru.itmo.java.message.tracker.TrackerResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ru.itmo.java.message.tracker.TrackerResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ru.itmo.java.message.tracker.TrackerResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ru.itmo.java.message.tracker.TrackerResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ru.itmo.java.message.tracker.TrackerResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ru.itmo.java.message.tracker.TrackerResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ru.itmo.java.message.tracker.TrackerResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ru.itmo.java.message.tracker.TrackerResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ru.itmo.java.message.tracker.TrackerResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ru.itmo.java.message.tracker.TrackerResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ru.itmo.java.message.tracker.TrackerResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ru.itmo.java.message.tracker.TrackerResponse)
      ru.itmo.java.message.tracker.TrackerResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ru.itmo.java.message.tracker.Torrent.internal_static_ru_itmo_java_message_tracker_TrackerResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ru.itmo.java.message.tracker.Torrent.internal_static_ru_itmo_java_message_tracker_TrackerResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ru.itmo.java.message.tracker.TrackerResponse.class, ru.itmo.java.message.tracker.TrackerResponse.Builder.class);
    }

    // Construct using ru.itmo.java.message.tracker.TrackerResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      responseCase_ = 0;
      response_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ru.itmo.java.message.tracker.Torrent.internal_static_ru_itmo_java_message_tracker_TrackerResponse_descriptor;
    }

    @java.lang.Override
    public ru.itmo.java.message.tracker.TrackerResponse getDefaultInstanceForType() {
      return ru.itmo.java.message.tracker.TrackerResponse.getDefaultInstance();
    }

    @java.lang.Override
    public ru.itmo.java.message.tracker.TrackerResponse build() {
      ru.itmo.java.message.tracker.TrackerResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ru.itmo.java.message.tracker.TrackerResponse buildPartial() {
      ru.itmo.java.message.tracker.TrackerResponse result = new ru.itmo.java.message.tracker.TrackerResponse(this);
      if (responseCase_ == 1) {
        if (listResponseBuilder_ == null) {
          result.response_ = response_;
        } else {
          result.response_ = listResponseBuilder_.build();
        }
      }
      if (responseCase_ == 2) {
        if (uploadResponseBuilder_ == null) {
          result.response_ = response_;
        } else {
          result.response_ = uploadResponseBuilder_.build();
        }
      }
      if (responseCase_ == 3) {
        if (sourceResponseBuilder_ == null) {
          result.response_ = response_;
        } else {
          result.response_ = sourceResponseBuilder_.build();
        }
      }
      if (responseCase_ == 4) {
        if (updateResponseBuilder_ == null) {
          result.response_ = response_;
        } else {
          result.response_ = updateResponseBuilder_.build();
        }
      }
      result.responseCase_ = responseCase_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ru.itmo.java.message.tracker.TrackerResponse) {
        return mergeFrom((ru.itmo.java.message.tracker.TrackerResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ru.itmo.java.message.tracker.TrackerResponse other) {
      if (other == ru.itmo.java.message.tracker.TrackerResponse.getDefaultInstance()) return this;
      switch (other.getResponseCase()) {
        case LISTRESPONSE: {
          mergeListResponse(other.getListResponse());
          break;
        }
        case UPLOADRESPONSE: {
          mergeUploadResponse(other.getUploadResponse());
          break;
        }
        case SOURCERESPONSE: {
          mergeSourceResponse(other.getSourceResponse());
          break;
        }
        case UPDATERESPONSE: {
          mergeUpdateResponse(other.getUpdateResponse());
          break;
        }
        case RESPONSE_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ru.itmo.java.message.tracker.TrackerResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ru.itmo.java.message.tracker.TrackerResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int responseCase_ = 0;
    private java.lang.Object response_;
    public ResponseCase
        getResponseCase() {
      return ResponseCase.forNumber(
          responseCase_);
    }

    public Builder clearResponse() {
      responseCase_ = 0;
      response_ = null;
      onChanged();
      return this;
    }


    private com.google.protobuf.SingleFieldBuilderV3<
        ru.itmo.java.message.tracker.ListResponse, ru.itmo.java.message.tracker.ListResponse.Builder, ru.itmo.java.message.tracker.ListResponseOrBuilder> listResponseBuilder_;
    /**
     * <code>.ru.itmo.java.message.tracker.ListResponse listResponse = 1;</code>
     * @return Whether the listResponse field is set.
     */
    @java.lang.Override
    public boolean hasListResponse() {
      return responseCase_ == 1;
    }
    /**
     * <code>.ru.itmo.java.message.tracker.ListResponse listResponse = 1;</code>
     * @return The listResponse.
     */
    @java.lang.Override
    public ru.itmo.java.message.tracker.ListResponse getListResponse() {
      if (listResponseBuilder_ == null) {
        if (responseCase_ == 1) {
          return (ru.itmo.java.message.tracker.ListResponse) response_;
        }
        return ru.itmo.java.message.tracker.ListResponse.getDefaultInstance();
      } else {
        if (responseCase_ == 1) {
          return listResponseBuilder_.getMessage();
        }
        return ru.itmo.java.message.tracker.ListResponse.getDefaultInstance();
      }
    }
    /**
     * <code>.ru.itmo.java.message.tracker.ListResponse listResponse = 1;</code>
     */
    public Builder setListResponse(ru.itmo.java.message.tracker.ListResponse value) {
      if (listResponseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        response_ = value;
        onChanged();
      } else {
        listResponseBuilder_.setMessage(value);
      }
      responseCase_ = 1;
      return this;
    }
    /**
     * <code>.ru.itmo.java.message.tracker.ListResponse listResponse = 1;</code>
     */
    public Builder setListResponse(
        ru.itmo.java.message.tracker.ListResponse.Builder builderForValue) {
      if (listResponseBuilder_ == null) {
        response_ = builderForValue.build();
        onChanged();
      } else {
        listResponseBuilder_.setMessage(builderForValue.build());
      }
      responseCase_ = 1;
      return this;
    }
    /**
     * <code>.ru.itmo.java.message.tracker.ListResponse listResponse = 1;</code>
     */
    public Builder mergeListResponse(ru.itmo.java.message.tracker.ListResponse value) {
      if (listResponseBuilder_ == null) {
        if (responseCase_ == 1 &&
            response_ != ru.itmo.java.message.tracker.ListResponse.getDefaultInstance()) {
          response_ = ru.itmo.java.message.tracker.ListResponse.newBuilder((ru.itmo.java.message.tracker.ListResponse) response_)
              .mergeFrom(value).buildPartial();
        } else {
          response_ = value;
        }
        onChanged();
      } else {
        if (responseCase_ == 1) {
          listResponseBuilder_.mergeFrom(value);
        }
        listResponseBuilder_.setMessage(value);
      }
      responseCase_ = 1;
      return this;
    }
    /**
     * <code>.ru.itmo.java.message.tracker.ListResponse listResponse = 1;</code>
     */
    public Builder clearListResponse() {
      if (listResponseBuilder_ == null) {
        if (responseCase_ == 1) {
          responseCase_ = 0;
          response_ = null;
          onChanged();
        }
      } else {
        if (responseCase_ == 1) {
          responseCase_ = 0;
          response_ = null;
        }
        listResponseBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.ru.itmo.java.message.tracker.ListResponse listResponse = 1;</code>
     */
    public ru.itmo.java.message.tracker.ListResponse.Builder getListResponseBuilder() {
      return getListResponseFieldBuilder().getBuilder();
    }
    /**
     * <code>.ru.itmo.java.message.tracker.ListResponse listResponse = 1;</code>
     */
    @java.lang.Override
    public ru.itmo.java.message.tracker.ListResponseOrBuilder getListResponseOrBuilder() {
      if ((responseCase_ == 1) && (listResponseBuilder_ != null)) {
        return listResponseBuilder_.getMessageOrBuilder();
      } else {
        if (responseCase_ == 1) {
          return (ru.itmo.java.message.tracker.ListResponse) response_;
        }
        return ru.itmo.java.message.tracker.ListResponse.getDefaultInstance();
      }
    }
    /**
     * <code>.ru.itmo.java.message.tracker.ListResponse listResponse = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ru.itmo.java.message.tracker.ListResponse, ru.itmo.java.message.tracker.ListResponse.Builder, ru.itmo.java.message.tracker.ListResponseOrBuilder> 
        getListResponseFieldBuilder() {
      if (listResponseBuilder_ == null) {
        if (!(responseCase_ == 1)) {
          response_ = ru.itmo.java.message.tracker.ListResponse.getDefaultInstance();
        }
        listResponseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ru.itmo.java.message.tracker.ListResponse, ru.itmo.java.message.tracker.ListResponse.Builder, ru.itmo.java.message.tracker.ListResponseOrBuilder>(
                (ru.itmo.java.message.tracker.ListResponse) response_,
                getParentForChildren(),
                isClean());
        response_ = null;
      }
      responseCase_ = 1;
      onChanged();;
      return listResponseBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        ru.itmo.java.message.tracker.UploadResponse, ru.itmo.java.message.tracker.UploadResponse.Builder, ru.itmo.java.message.tracker.UploadResponseOrBuilder> uploadResponseBuilder_;
    /**
     * <code>.ru.itmo.java.message.tracker.UploadResponse uploadResponse = 2;</code>
     * @return Whether the uploadResponse field is set.
     */
    @java.lang.Override
    public boolean hasUploadResponse() {
      return responseCase_ == 2;
    }
    /**
     * <code>.ru.itmo.java.message.tracker.UploadResponse uploadResponse = 2;</code>
     * @return The uploadResponse.
     */
    @java.lang.Override
    public ru.itmo.java.message.tracker.UploadResponse getUploadResponse() {
      if (uploadResponseBuilder_ == null) {
        if (responseCase_ == 2) {
          return (ru.itmo.java.message.tracker.UploadResponse) response_;
        }
        return ru.itmo.java.message.tracker.UploadResponse.getDefaultInstance();
      } else {
        if (responseCase_ == 2) {
          return uploadResponseBuilder_.getMessage();
        }
        return ru.itmo.java.message.tracker.UploadResponse.getDefaultInstance();
      }
    }
    /**
     * <code>.ru.itmo.java.message.tracker.UploadResponse uploadResponse = 2;</code>
     */
    public Builder setUploadResponse(ru.itmo.java.message.tracker.UploadResponse value) {
      if (uploadResponseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        response_ = value;
        onChanged();
      } else {
        uploadResponseBuilder_.setMessage(value);
      }
      responseCase_ = 2;
      return this;
    }
    /**
     * <code>.ru.itmo.java.message.tracker.UploadResponse uploadResponse = 2;</code>
     */
    public Builder setUploadResponse(
        ru.itmo.java.message.tracker.UploadResponse.Builder builderForValue) {
      if (uploadResponseBuilder_ == null) {
        response_ = builderForValue.build();
        onChanged();
      } else {
        uploadResponseBuilder_.setMessage(builderForValue.build());
      }
      responseCase_ = 2;
      return this;
    }
    /**
     * <code>.ru.itmo.java.message.tracker.UploadResponse uploadResponse = 2;</code>
     */
    public Builder mergeUploadResponse(ru.itmo.java.message.tracker.UploadResponse value) {
      if (uploadResponseBuilder_ == null) {
        if (responseCase_ == 2 &&
            response_ != ru.itmo.java.message.tracker.UploadResponse.getDefaultInstance()) {
          response_ = ru.itmo.java.message.tracker.UploadResponse.newBuilder((ru.itmo.java.message.tracker.UploadResponse) response_)
              .mergeFrom(value).buildPartial();
        } else {
          response_ = value;
        }
        onChanged();
      } else {
        if (responseCase_ == 2) {
          uploadResponseBuilder_.mergeFrom(value);
        }
        uploadResponseBuilder_.setMessage(value);
      }
      responseCase_ = 2;
      return this;
    }
    /**
     * <code>.ru.itmo.java.message.tracker.UploadResponse uploadResponse = 2;</code>
     */
    public Builder clearUploadResponse() {
      if (uploadResponseBuilder_ == null) {
        if (responseCase_ == 2) {
          responseCase_ = 0;
          response_ = null;
          onChanged();
        }
      } else {
        if (responseCase_ == 2) {
          responseCase_ = 0;
          response_ = null;
        }
        uploadResponseBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.ru.itmo.java.message.tracker.UploadResponse uploadResponse = 2;</code>
     */
    public ru.itmo.java.message.tracker.UploadResponse.Builder getUploadResponseBuilder() {
      return getUploadResponseFieldBuilder().getBuilder();
    }
    /**
     * <code>.ru.itmo.java.message.tracker.UploadResponse uploadResponse = 2;</code>
     */
    @java.lang.Override
    public ru.itmo.java.message.tracker.UploadResponseOrBuilder getUploadResponseOrBuilder() {
      if ((responseCase_ == 2) && (uploadResponseBuilder_ != null)) {
        return uploadResponseBuilder_.getMessageOrBuilder();
      } else {
        if (responseCase_ == 2) {
          return (ru.itmo.java.message.tracker.UploadResponse) response_;
        }
        return ru.itmo.java.message.tracker.UploadResponse.getDefaultInstance();
      }
    }
    /**
     * <code>.ru.itmo.java.message.tracker.UploadResponse uploadResponse = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ru.itmo.java.message.tracker.UploadResponse, ru.itmo.java.message.tracker.UploadResponse.Builder, ru.itmo.java.message.tracker.UploadResponseOrBuilder> 
        getUploadResponseFieldBuilder() {
      if (uploadResponseBuilder_ == null) {
        if (!(responseCase_ == 2)) {
          response_ = ru.itmo.java.message.tracker.UploadResponse.getDefaultInstance();
        }
        uploadResponseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ru.itmo.java.message.tracker.UploadResponse, ru.itmo.java.message.tracker.UploadResponse.Builder, ru.itmo.java.message.tracker.UploadResponseOrBuilder>(
                (ru.itmo.java.message.tracker.UploadResponse) response_,
                getParentForChildren(),
                isClean());
        response_ = null;
      }
      responseCase_ = 2;
      onChanged();;
      return uploadResponseBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        ru.itmo.java.message.tracker.SourceResponse, ru.itmo.java.message.tracker.SourceResponse.Builder, ru.itmo.java.message.tracker.SourceResponseOrBuilder> sourceResponseBuilder_;
    /**
     * <code>.ru.itmo.java.message.tracker.SourceResponse sourceResponse = 3;</code>
     * @return Whether the sourceResponse field is set.
     */
    @java.lang.Override
    public boolean hasSourceResponse() {
      return responseCase_ == 3;
    }
    /**
     * <code>.ru.itmo.java.message.tracker.SourceResponse sourceResponse = 3;</code>
     * @return The sourceResponse.
     */
    @java.lang.Override
    public ru.itmo.java.message.tracker.SourceResponse getSourceResponse() {
      if (sourceResponseBuilder_ == null) {
        if (responseCase_ == 3) {
          return (ru.itmo.java.message.tracker.SourceResponse) response_;
        }
        return ru.itmo.java.message.tracker.SourceResponse.getDefaultInstance();
      } else {
        if (responseCase_ == 3) {
          return sourceResponseBuilder_.getMessage();
        }
        return ru.itmo.java.message.tracker.SourceResponse.getDefaultInstance();
      }
    }
    /**
     * <code>.ru.itmo.java.message.tracker.SourceResponse sourceResponse = 3;</code>
     */
    public Builder setSourceResponse(ru.itmo.java.message.tracker.SourceResponse value) {
      if (sourceResponseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        response_ = value;
        onChanged();
      } else {
        sourceResponseBuilder_.setMessage(value);
      }
      responseCase_ = 3;
      return this;
    }
    /**
     * <code>.ru.itmo.java.message.tracker.SourceResponse sourceResponse = 3;</code>
     */
    public Builder setSourceResponse(
        ru.itmo.java.message.tracker.SourceResponse.Builder builderForValue) {
      if (sourceResponseBuilder_ == null) {
        response_ = builderForValue.build();
        onChanged();
      } else {
        sourceResponseBuilder_.setMessage(builderForValue.build());
      }
      responseCase_ = 3;
      return this;
    }
    /**
     * <code>.ru.itmo.java.message.tracker.SourceResponse sourceResponse = 3;</code>
     */
    public Builder mergeSourceResponse(ru.itmo.java.message.tracker.SourceResponse value) {
      if (sourceResponseBuilder_ == null) {
        if (responseCase_ == 3 &&
            response_ != ru.itmo.java.message.tracker.SourceResponse.getDefaultInstance()) {
          response_ = ru.itmo.java.message.tracker.SourceResponse.newBuilder((ru.itmo.java.message.tracker.SourceResponse) response_)
              .mergeFrom(value).buildPartial();
        } else {
          response_ = value;
        }
        onChanged();
      } else {
        if (responseCase_ == 3) {
          sourceResponseBuilder_.mergeFrom(value);
        }
        sourceResponseBuilder_.setMessage(value);
      }
      responseCase_ = 3;
      return this;
    }
    /**
     * <code>.ru.itmo.java.message.tracker.SourceResponse sourceResponse = 3;</code>
     */
    public Builder clearSourceResponse() {
      if (sourceResponseBuilder_ == null) {
        if (responseCase_ == 3) {
          responseCase_ = 0;
          response_ = null;
          onChanged();
        }
      } else {
        if (responseCase_ == 3) {
          responseCase_ = 0;
          response_ = null;
        }
        sourceResponseBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.ru.itmo.java.message.tracker.SourceResponse sourceResponse = 3;</code>
     */
    public ru.itmo.java.message.tracker.SourceResponse.Builder getSourceResponseBuilder() {
      return getSourceResponseFieldBuilder().getBuilder();
    }
    /**
     * <code>.ru.itmo.java.message.tracker.SourceResponse sourceResponse = 3;</code>
     */
    @java.lang.Override
    public ru.itmo.java.message.tracker.SourceResponseOrBuilder getSourceResponseOrBuilder() {
      if ((responseCase_ == 3) && (sourceResponseBuilder_ != null)) {
        return sourceResponseBuilder_.getMessageOrBuilder();
      } else {
        if (responseCase_ == 3) {
          return (ru.itmo.java.message.tracker.SourceResponse) response_;
        }
        return ru.itmo.java.message.tracker.SourceResponse.getDefaultInstance();
      }
    }
    /**
     * <code>.ru.itmo.java.message.tracker.SourceResponse sourceResponse = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ru.itmo.java.message.tracker.SourceResponse, ru.itmo.java.message.tracker.SourceResponse.Builder, ru.itmo.java.message.tracker.SourceResponseOrBuilder> 
        getSourceResponseFieldBuilder() {
      if (sourceResponseBuilder_ == null) {
        if (!(responseCase_ == 3)) {
          response_ = ru.itmo.java.message.tracker.SourceResponse.getDefaultInstance();
        }
        sourceResponseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ru.itmo.java.message.tracker.SourceResponse, ru.itmo.java.message.tracker.SourceResponse.Builder, ru.itmo.java.message.tracker.SourceResponseOrBuilder>(
                (ru.itmo.java.message.tracker.SourceResponse) response_,
                getParentForChildren(),
                isClean());
        response_ = null;
      }
      responseCase_ = 3;
      onChanged();;
      return sourceResponseBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        ru.itmo.java.message.tracker.UpdateResponse, ru.itmo.java.message.tracker.UpdateResponse.Builder, ru.itmo.java.message.tracker.UpdateResponseOrBuilder> updateResponseBuilder_;
    /**
     * <code>.ru.itmo.java.message.tracker.UpdateResponse updateResponse = 4;</code>
     * @return Whether the updateResponse field is set.
     */
    @java.lang.Override
    public boolean hasUpdateResponse() {
      return responseCase_ == 4;
    }
    /**
     * <code>.ru.itmo.java.message.tracker.UpdateResponse updateResponse = 4;</code>
     * @return The updateResponse.
     */
    @java.lang.Override
    public ru.itmo.java.message.tracker.UpdateResponse getUpdateResponse() {
      if (updateResponseBuilder_ == null) {
        if (responseCase_ == 4) {
          return (ru.itmo.java.message.tracker.UpdateResponse) response_;
        }
        return ru.itmo.java.message.tracker.UpdateResponse.getDefaultInstance();
      } else {
        if (responseCase_ == 4) {
          return updateResponseBuilder_.getMessage();
        }
        return ru.itmo.java.message.tracker.UpdateResponse.getDefaultInstance();
      }
    }
    /**
     * <code>.ru.itmo.java.message.tracker.UpdateResponse updateResponse = 4;</code>
     */
    public Builder setUpdateResponse(ru.itmo.java.message.tracker.UpdateResponse value) {
      if (updateResponseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        response_ = value;
        onChanged();
      } else {
        updateResponseBuilder_.setMessage(value);
      }
      responseCase_ = 4;
      return this;
    }
    /**
     * <code>.ru.itmo.java.message.tracker.UpdateResponse updateResponse = 4;</code>
     */
    public Builder setUpdateResponse(
        ru.itmo.java.message.tracker.UpdateResponse.Builder builderForValue) {
      if (updateResponseBuilder_ == null) {
        response_ = builderForValue.build();
        onChanged();
      } else {
        updateResponseBuilder_.setMessage(builderForValue.build());
      }
      responseCase_ = 4;
      return this;
    }
    /**
     * <code>.ru.itmo.java.message.tracker.UpdateResponse updateResponse = 4;</code>
     */
    public Builder mergeUpdateResponse(ru.itmo.java.message.tracker.UpdateResponse value) {
      if (updateResponseBuilder_ == null) {
        if (responseCase_ == 4 &&
            response_ != ru.itmo.java.message.tracker.UpdateResponse.getDefaultInstance()) {
          response_ = ru.itmo.java.message.tracker.UpdateResponse.newBuilder((ru.itmo.java.message.tracker.UpdateResponse) response_)
              .mergeFrom(value).buildPartial();
        } else {
          response_ = value;
        }
        onChanged();
      } else {
        if (responseCase_ == 4) {
          updateResponseBuilder_.mergeFrom(value);
        }
        updateResponseBuilder_.setMessage(value);
      }
      responseCase_ = 4;
      return this;
    }
    /**
     * <code>.ru.itmo.java.message.tracker.UpdateResponse updateResponse = 4;</code>
     */
    public Builder clearUpdateResponse() {
      if (updateResponseBuilder_ == null) {
        if (responseCase_ == 4) {
          responseCase_ = 0;
          response_ = null;
          onChanged();
        }
      } else {
        if (responseCase_ == 4) {
          responseCase_ = 0;
          response_ = null;
        }
        updateResponseBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.ru.itmo.java.message.tracker.UpdateResponse updateResponse = 4;</code>
     */
    public ru.itmo.java.message.tracker.UpdateResponse.Builder getUpdateResponseBuilder() {
      return getUpdateResponseFieldBuilder().getBuilder();
    }
    /**
     * <code>.ru.itmo.java.message.tracker.UpdateResponse updateResponse = 4;</code>
     */
    @java.lang.Override
    public ru.itmo.java.message.tracker.UpdateResponseOrBuilder getUpdateResponseOrBuilder() {
      if ((responseCase_ == 4) && (updateResponseBuilder_ != null)) {
        return updateResponseBuilder_.getMessageOrBuilder();
      } else {
        if (responseCase_ == 4) {
          return (ru.itmo.java.message.tracker.UpdateResponse) response_;
        }
        return ru.itmo.java.message.tracker.UpdateResponse.getDefaultInstance();
      }
    }
    /**
     * <code>.ru.itmo.java.message.tracker.UpdateResponse updateResponse = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ru.itmo.java.message.tracker.UpdateResponse, ru.itmo.java.message.tracker.UpdateResponse.Builder, ru.itmo.java.message.tracker.UpdateResponseOrBuilder> 
        getUpdateResponseFieldBuilder() {
      if (updateResponseBuilder_ == null) {
        if (!(responseCase_ == 4)) {
          response_ = ru.itmo.java.message.tracker.UpdateResponse.getDefaultInstance();
        }
        updateResponseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ru.itmo.java.message.tracker.UpdateResponse, ru.itmo.java.message.tracker.UpdateResponse.Builder, ru.itmo.java.message.tracker.UpdateResponseOrBuilder>(
                (ru.itmo.java.message.tracker.UpdateResponse) response_,
                getParentForChildren(),
                isClean());
        response_ = null;
      }
      responseCase_ = 4;
      onChanged();;
      return updateResponseBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ru.itmo.java.message.tracker.TrackerResponse)
  }

  // @@protoc_insertion_point(class_scope:ru.itmo.java.message.tracker.TrackerResponse)
  private static final ru.itmo.java.message.tracker.TrackerResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ru.itmo.java.message.tracker.TrackerResponse();
  }

  public static ru.itmo.java.message.tracker.TrackerResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TrackerResponse>
      PARSER = new com.google.protobuf.AbstractParser<TrackerResponse>() {
    @java.lang.Override
    public TrackerResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TrackerResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TrackerResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TrackerResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ru.itmo.java.message.tracker.TrackerResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

