// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gen/Torrent.proto

package ru.itmo.java.message.tracker;

public interface UploadRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ru.itmo.java.message.tracker.UploadRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.ru.itmo.java.message.tracker.FileData file = 1;</code>
   * @return Whether the file field is set.
   */
  boolean hasFile();
  /**
   * <code>.ru.itmo.java.message.tracker.FileData file = 1;</code>
   * @return The file.
   */
  ru.itmo.java.message.tracker.FileData getFile();
  /**
   * <code>.ru.itmo.java.message.tracker.FileData file = 1;</code>
   */
  ru.itmo.java.message.tracker.FileDataOrBuilder getFileOrBuilder();
}
